Add ability to draw parts of area with different colors
tradingview/lightweight-charts pull request #1101
Opened 2022-06-28 18:02 UTC by kirchet

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #1100 
- [x] Includes tests
- [x] Documentation update

2022-06-29 09:33 UTC, romfrancois submitted a review, later dismissed
Looks good to me but probably best to have an expert opinion :)

2022-07-04 09:09 UTC, eugene-korobko requested changes

2022-07-04 10:30 UTC, kirchet commented on src/renderers/line-renderer-base.ts
> +function finishStyledArea(ctx: CanvasRenderingContext2D, style: CanvasRenderingContext2D['strokeStyle']): void {
Why? Area is used here as piece, part

2022-07-04 11:18 UTC, kirchet commented on src/renderers/walk-line.ts
> +	const firstItem = items[visibleRange.from];
Fixed

2022-07-05 09:56 UTC, eugene-korobko approved these changes

2022-07-06 13:54 UTC, eugene-korobko approved these changes

2022-07-15 13:44 UTC, merged