Horizontal scroll animations improvements
tradingview/lightweight-charts pull request #1140
Opened 2022-08-05 15:07 UTC by kirchet

**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #1136
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**

![scroll_animation](https://user-images.githubusercontent.com/1572087/183106046-52314872-eafd-4546-a936-b3c24c57eef5.gif)

2022-08-11 13:04 UTC, Nipheris requested changes

2022-08-11 13:04 UTC, Nipheris commented on src/model/time-scale.ts
> +				requestAnimationFrame(animationFn);
`requestAnimationFrame` in a `TimeScale`.. Sounds more like a job for `PaneWidget`. And, btw, we already have animation logic there, why not make it generic for both types of animation?

I suggest you to move both `KineticAnimation` and this uniform animation objects back to PaneWidget, and use some generic interface for animations like:
- finished(time)
- terminated
- getPosition(time).

Then use `model.scrollTimeTo` or `timeScale.setRightOffset` (not sure what fits better) to update the model according to current animation, like we already do in `PaneWidget`: `model.scrollTimeTo(scrollXAnimation.getPosition(now));`

2022-08-11 13:04 UTC, Nipheris commented on src/model/time-scale.ts
>  			const animationProgress = (performance.now() - animationStart) / animationDuration;
A sidenote: it is better to use the `time` argument passed to `animationFn` by `requestAnimationFrame` to get the "current" time. Nevertheless, `performance.now()` should still be used to capture "start" time.

2022-08-12 11:27 UTC, kirchet commented on src/gui/pane-widget.ts
>  				// animation terminated, see _terminateKineticAnimation
Fixed

2022-08-12 11:28 UTC, kirchet commented on src/model/time-scale.ts
> +			terminate: () => {
https://github.com/tradingview/lightweight-charts/pull/1140/commits/33e10e99d5dbb791b1cf13f4b7891e244d071127

2022-08-12 11:28 UTC, kirchet commented on src/model/time-scale.ts
> +				requestAnimationFrame(animationFn);
https://github.com/tradingview/lightweight-charts/pull/1140/commits/33e10e99d5dbb791b1cf13f4b7891e244d071127

2022-08-12 11:28 UTC, kirchet commented on src/model/time-scale.ts
>  			const animationProgress = (performance.now() - animationStart) / animationDuration;
Fixed

2022-08-12 13:02 UTC, Nipheris approved these changes

2022-08-16 13:40 UTC, merged