New Documentation Landing Page
tradingview/lightweight-charts pull request #1261
Opened 2023-02-06 23:25 UTC by SlicedSilver

**Type of PR:** enhancement

**PR checklist:**

- `N/A` Addresses an existing issue: fixes #
- `N/A` Includes tests
- [x] Documentation update

**Overview of change:**
- Implements the new landing page design.
- Includes updates to the tutorial examples for v4.0 release
- Added release notes documentation page

2023-02-07 11:24 UTC, romfrancois approved these changes

2023-02-07 11:33 UTC, romfrancois requested changes

2023-02-07 11:33 UTC, romfrancois commented on website/tutorials/how_to/legends.mdx
> +        const price = data.value !== undefined ? data.value : data.close;
Looks like price is not displayed in the legend. Instead there's NaN

2023-02-07 11:46 UTC, SlicedSilver commented on website/tutorials/how_to/legends.mdx
> +        const price = data.value !== undefined ? data.value : data.close;
Should be resolved with the latest commit. I'll update the preview page shortly.

2023-02-07 11:50 UTC, romfrancois approved these changes

2023-02-07 19:23 UTC, romfrancois approved these changes

2023-02-08 13:10 UTC, romfrancois approved these changes

2023-02-08 13:10 UTC, merged