fix unable to add markers when autoSize chart option is enabled
tradingview/lightweight-charts pull request #1281
Opened 2023-02-22 22:25 UTC by victorbrambati

**Type of PR:** bugfix

**PR checklist:**

* [x] Addresses an existing issue: fixes #1271 
* `N/A` ~Includes tests~
* `N/A`  ~Documentation update~

**Overview of change:**
* The function `timeScale.isEmpty()` was returning true. This because there a condition with a `width === 0`. To resolve this [issue](https://github.com/tradingview/lightweight-charts/issues/1271), an initial size was added so that the markers could be recalculated.
* I changed the condition of `_recalculateMarkers()` to be easier to read.

**Glitch Code Sandbox link:**
https://glitch.com/edit/#!/hurricane-mahogany-output

2023-02-22 23:38 UTC, SlicedSilver commented
@victorbrambati Thank you for your PR.
Having a quick look at the `graphics-tests` it appears that this additional fixes another bug I've noticed regarding the initial render not having the correct right offset (the last few bars aren't visible). 

We will conduct the code review and QA process before merging, but this will hopefully be done soon.

2023-02-23 15:44 UTC, victorbrambati commented
@SlicedSilver Surprising! Any changes that you need, you can reply me.

2023-02-23 19:13 UTC, SlicedSilver commented on src/gui/chart-widget.ts
> +			this.resize(width, height);
Since the resize method is now being called if `usedObserver` is `true` or `false`.

Could we remove `this.resize` from within this `if` block and rather remove the `if (!usedObserver)` condition below?

```js
// replace this:
if (!usedObserver) {
	this.resize(width, height);
}
```
```js
// with this:
this.resize(width, height);
```

2023-02-23 19:40 UTC, victorbrambati commented on src/gui/chart-widget.ts
> +			this.resize(width, height);
Yes, have the same effect.

2023-02-23 19:48 UTC, SlicedSilver commented on src/gui/chart-widget.ts
> +			this.resize(width, height);
Thank you

2023-02-23 19:51 UTC, SlicedSilver commented
@victorbrambati I also think it would be good to have a graphics e2e test case which covers this bug. 
Is this something that you would like to work on? or would you prefer me to add the test to your PR?

I'm happy to do it but wanted to check first if you wanted to work on this.

2023-02-23 19:56 UTC, victorbrambati commented
@SlicedSilver Yes I want work on it.

2023-02-23 21:52 UTC, SlicedSilver commented
> @SlicedSilver Yes I want work on it.

Great :) Thank you.

Here is a some documentation on the graphics tests: https://github.com/tradingview/lightweight-charts/tree/master/tests#graphics

You essentially just need to make a `.js` file inside this folder: [`tests/e2e/graphics/test-cases`](https://github.com/tradingview/lightweight-charts/tree/master/tests/e2e/graphics/test-cases)

There are some examples there which you can use for inspiration, and you could do something similar to the Glitch example on the bug report.

2023-02-24 22:11 UTC, SlicedSilver commented
Thank you @victorbrambati 
The tests look good. You can clearly see that it failed on the current release (v4.0.0) and is fixed on your branch.

Golden:
![1 golden](https://user-images.githubusercontent.com/3482679/221302973-a1101a0d-b944-4538-90e1-0e9a03a51bad.png)

Test:
![2 test](https://user-images.githubusercontent.com/3482679/221302971-59a74268-28ab-44aa-888b-d23105b74faa.png)

2023-02-24 22:13 UTC, SlicedSilver approved these changes

2023-02-24 23:04 UTC, victorbrambati commented
@SlicedSilver You're welcome.
This test too work to issue #1282 because the priceline is different.

2023-03-14 14:29 UTC, kirchet requested changes

2023-03-14 14:29 UTC, kirchet commented on src/model/series.ts
> +		if (timeScale.isEmpty() || this._data.isEmpty()) {
We need `timeScale` here to call `timeToIndex`.
```
const timePointIndex = ensureNotNull(timeScale.timeToIndex(marker.time, true));
```

So actually we should check that we can convert time to index.
```suggestion
		if (!timeScale.hasPoints() || this._data.isEmpty()) {
```

For now there is no `TimeScale.hasPoints` method, we need to implement it

```
public hasPoints(): boolean {
	return this._points.length > 0;
}
```

2023-03-14 14:29 UTC, kirchet commented on src/gui/chart-widget.ts
> +		this.resize(width, height);
This change seems unrelated to the issue and should be reverted

2023-03-14 15:04 UTC, SlicedSilver commented on src/gui/chart-widget.ts
> +		this.resize(width, height);
Agree that the change isn't directly related to the markers issue but this change is still needed to address #1282.

This can be seen with the `initial-options/use-observer` test-case. https://app.circleci.com/pipelines/github/tradingview/lightweight-charts/1942/workflows/17dd9cbf-9dc1-4e7c-95ed-e3098cc57ae0/jobs/25041/artifacts

If I revert the change above then that test will pass again (showing the old incorrect behaviour) but in this case we want it to fail.

2023-03-15 17:20 UTC, merged