Horz scale as numbers
tradingview/lightweight-charts pull request #1323
Opened 2023-04-04 07:17 UTC by eugene-korobko

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #1322
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**

This is the very first approach of implementing non time-based horizontal scale

**Is there anything you'd like reviewers to focus on?**

I believe we have to try keeping interfaces unchaged as mush as possible

2023-07-19 13:01 UTC, Nipheris requested changes

2023-07-19 13:01 UTC, Nipheris commented on src/api/candlestick-series-api.ts
> +export class CandlestickSeriesApi<HorzScaleItem> extends SeriesApi<'Candlestick', HorzScaleItem> {
What about renaming `HorzScaleItem` to `Abscissa` everywhere? I think we need some simple term here.

2023-07-24 14:20 UTC, eugene-korobko commented on src/model/horz-scale-behavior-time/horz-scale-behavior-time.ts
> +export class HorzScaleBehaviorTime implements IHorzScaleBehavior<Time> {
Sorry, chould you please clarify the idea? What scale classes inheritance do you mean?

2023-07-24 14:28 UTC, eugene-korobko commented on src/model/time-data.ts
>  export type TimePointIndex = Nominal<number, 'TimePointIndex'>;
This type exists in the typing. Each renaming is a breaking change. And, I believe, non-time horizontal scale will be used by 1% of users. So, I'm not sure it is good idea to rename public classes

2023-08-16 13:45 UTC, Nipheris approved these changes

2023-08-16 13:52 UTC, merged