Use label length when building marks
tradingview/lightweight-charts pull request #1409
Opened 2023-08-22 08:29 UTC by edew

**Type of PR:** 

**PR checklist:**

- [x] Addresses an existing issue: fixes #1396 
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Use the label length when building tick marks.

These changes stop overlapping labels, but it is a breaking change as it does not preserve the existing time scale behaviour.

**Is there anything you'd like reviewers to focus on?**

2023-08-22 09:04 UTC, SlicedSilver commented
Whether this is a 'breaking change' is debatable. It doesn't change the API so everyone's charts should continue to work. The difference is when the time scale labels are either shorter than 8 character (then it is possible for more tick marks & grid lines to appear), or when they are longer than 8 characters.

IMO I don't think it is a true breaking change, and could be included in a minor release.

2023-08-22 09:06 UTC, edew commented
> Whether this is a 'breaking change' is debatable. It doesn't change the API so everyone's charts should continue to work. The difference is when the time scale labels are either shorter than 8 character (then it is possible for more tick marks & grid lines to appear), or when they are longer than 8 characters.
> 
> IMO I don't think it is a true breaking change, and could be included in a minor release.

Agreed, maybe breaking change is the wrong way of putting it.

If we were to merge this I don't think it needs a major release.

2023-08-22 09:09 UTC, edew commented on src/model/tick-marks.ts
> +function roundToOneDecimalPlace(n: number): number {
Why round to one decimal place?

If we do not then even very small changes in the spacing will cause the marks to be rebuilt. Limiting this to increments of 0.1 seems to be an acceptable compromise but probably there is a cleverer way to handle this.

2023-08-25 15:59 UTC, SlicedSilver commented on src/model/tick-marks.ts
> +		const defaultMaxIndexesPerMark = roundToOneDecimalPlace(maxLabelWidth / spacing);
```suggestion
		// Why round to one decimal place?
		// If we do not then even very small changes in the spacing will cause the marks to be rebuilt. Limiting this to increments of 0.1 seems to be an acceptable compromise.
		const defaultMaxIndexesPerMark = roundToOneDecimalPlace(maxLabelWidth / spacing);
```

2023-08-25 15:59 UTC, SlicedSilver commented on .size-limit.js
> +		limit: '49.40 KB',
We should set these values as 0.01 higher than the number we get when running the size check.
The reason is that the size can change very slightly on each build because we include the build date as a comment in the output. This seems to affect the compressed size (some dates are more compressible than others).

I suggest these numbers:
47.69
47.64
49.36
49.41

and it would probably be a good idea to add a comment to the top of this files which explains this. Because it is not obvious.

2023-08-31 18:00 UTC, SlicedSilver approved these changes

2023-09-13 08:18 UTC, 0220tiezo1323 requested changes
Asp

2023-09-19 09:12 UTC, closed without merging