Add option to set minimum dimension for scales
tradingview/lightweight-charts pull request #1412
Opened 2023-08-23 09:44 UTC by SlicedSilver

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #1062 (related: #1163, #50)
- [x] Includes tests
- [x] Documentation update

**Overview of change:**
Adds options to set minimum dimensions for the price and time scales.

Setting a minimum height / width is useful for ensuring that multiple charts positioned in a vertical / horizontal stack each have an identical price scale width (or time scale height), or for plugins which require a bit more space within the scale pane.

The minimum dimension is only considered when that scale should be visible, and also it can be exceeded if the scale needs more space.

2023-09-13 08:16 UTC, 0220tiezo1323 requested changes
Pay changes need

2023-09-18 09:49 UTC, edew approved these changes

2023-09-18 09:52 UTC, 0220tiezo1323 approved these changes

2023-09-18 09:53 UTC, edew commented
The d.ts changes are expected

```
diff --git a/./dts-changes/base.d.ts b/./dts-changes/compare.d.ts
index 5670b54c..ac83c537 100644
--- a/./dts-changes/base.d.ts
+++ b/./dts-changes/compare.d.ts
@@ -1147,6 +1147,19 @@ export interface HorzScaleOptions {
         * With this flag equal to `true`, marks of the same weight are either all drawn or none are drawn at all.
         */
        uniformDistribution: boolean;
+       /**
+        * Define a minimum height for the time scale.
+        * Note: This value will be exceeded if the
+        * time scale needs more space to display it's contents.
+        *
+        * Setting a minimum height could be useful for ensuring that
+        * multiple charts positioned in a horizontal stack each have
+        * an identical time scale height, or for plugins which
+        * require a bit more space within the time scale pane.
+        *
+        * @defaultValue 0
+        */
+       minimumHeight: number;
 }
 /**
  * The main interface of a single chart using time for horizontal scale.
@@ -2720,6 +2733,19 @@ export interface PriceScaleOptions {
         * @defaultValue `false`
         */
        ticksVisible: boolean;
+       /**
+        * Define a minimum width for the price scale.
+        * Note: This value will be exceeded if the
+        * price scale needs more space to display it's contents.
+        *
+        * Setting a minimum width could be useful for ensuring that
+        * multiple charts positioned in a vertical stack each have
+        * an identical price scale width, or for plugins which
+        * require a bit more space within the price scale pane.
+        *
+        * @defaultValue 0
+        */
+       minimumWidth: number;
```

2023-09-19 09:11 UTC, merged