Fix react tutorial bug
tradingview/lightweight-charts pull request #1535
Opened 2024-03-06 14:05 UTC by illetid

**Type of PR:**  bugfix

**PR checklist:**

- [ ] Addresses an existing issue: fixes #
- [ ] Includes tests
- [x] Documentation update

**Overview of change:**
Fix a bug in the react advanced tutorial. It was caused by the call of the chart `.remove()` method twice. I've added a `removeSeries` call to a `Series` component unmount callback to remove the correct series and added a button to toggle second series component to showcase `Series` component cleanup

2024-03-06 14:49 UTC, SlicedSilver commented
How do you feel about changing the tabs to spaces when rendering the code within the documentation page?
Currently I feel that the tabs on that example are way too large and make the code harder to read.

For example, as a simple fix we could modify this line:
https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/website/tutorials/react/02-advanced.mdx#L224
to be:
```mdx
<CodeBlock replaceThemeConstants className="language-jsx">{code.replace(/\t/g,'    ')}</CodeBlock>
```
<img width="1014" alt="Screenshot 2024-03-06 at 14 48 13" src="https://github.com/tradingview/lightweight-charts/assets/3482679/d2e47caf-e49b-497d-994b-7325c3c65731">
<img width="1014" alt="Screenshot 2024-03-06 at 14 47 58" src="https://github.com/tradingview/lightweight-charts/assets/3482679/79ba3c8e-90b4-4879-9d00-55f2545caa9b">

2024-03-06 14:50 UTC, SlicedSilver commented
[Optional] It might be nice to also update the second series in the example.

[!video](https://github.com/tradingview/lightweight-charts/assets/3482679/8a963a9a-e9a6-41fb-802a-35fa138581f7)

2024-03-06 14:53 UTC, SlicedSilver submitted a review, later dismissed
The code changes look good. The other comments are optional (if you feel like they make sense to implement).

2024-03-06 14:53 UTC, SlicedSilver commented on website/src/css/custom.css
> +
Thanks for fixing this 👍

2024-03-07 11:49 UTC, romfrancois submitted a review, later dismissed

2024-03-07 12:08 UTC, illetid commented
@SlicedSilver thanks for the suggestions, added update functionality for 2nd line and replaced tab to spaces

2024-03-07 12:19 UTC, SlicedSilver requested changes

2024-03-07 12:19 UTC, SlicedSilver commented on website/tutorials/react/02-advanced.mdx
> +<CodeBlock replaceThemeConstants className="language-jsx">{code.replace(/\t/g, '    ')}</CodeBlock>
Actually, lets do this change within the `<CodeBlock>` element ([`website/plugins/enhanced-codeblock/theme/CodeBlock/index.jsx`](https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/website/plugins/enhanced-codeblock/theme/CodeBlock/index.jsx#L38-L40)) so that the change is consistently applied to all codeblocks which are using js files loaded via `"!!raw-loader!"`. We use the `<CodeBlock>` in multiple mdx files (like [website/tutorials/how_to/legends.mdx](https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/website/tutorials/how_to/legends.mdx)).

A bit like we have done here: https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/website/plugins/enhanced-codeblock/theme/CodeBlock/index.jsx#L38-L40

2024-03-07 12:44 UTC, illetid commented on website/tutorials/react/02-advanced.mdx
> +<CodeBlock replaceThemeConstants className="language-jsx">{code.replace(/\t/g, '    ')}</CodeBlock>
totally makes sense, added a `replaceTabs` prop to `CodeBlock` and made it `true` by default so changes will apply in all places and we can opt out if we need somewhere

2024-03-07 12:53 UTC, SlicedSilver commented on website/tutorials/react/02-advanced.mdx
> +<CodeBlock replaceThemeConstants replaceTabs className="language-jsx">{code}</CodeBlock>
If it is now on by default then we can remove `replaceTabs` here.
```suggestion
<CodeBlock replaceThemeConstants className="language-jsx">{code}</CodeBlock>
```

2024-03-07 12:55 UTC, illetid commented on website/tutorials/react/02-advanced.mdx
> +<CodeBlock replaceThemeConstants replaceTabs className="language-jsx">{code}</CodeBlock>
removed, thanks

2024-03-07 12:56 UTC, SlicedSilver approved these changes

2024-03-07 12:56 UTC, SlicedSilver commented
We can merge this later this afternoon 👍

2024-03-07 14:07 UTC, romfrancois approved these changes

2024-03-08 11:31 UTC, merged