fix: markers margin adjustment
tradingview/lightweight-charts pull request #1539
Opened 2024-03-12 09:30 UTC by illetid

added @kirchet  suggestions from  #1538

2024-03-12 12:56 UTC, kirchet requested changes

2024-03-12 12:56 UTC, kirchet commented on src/views/pane/series-markers-pane-view.ts
> +			this._makersPositions = this._getMarkerPositions();
To not mix immediate and lazy updates we need just invalidate markers positions state here. We can set `_markersPositions` to `null` here and update them in `_getMarkerPositions`

```TS
private getMarkersPositions(): MarkerPositions {
  if (this._markersPositions === null) {
    this._markersPositions = ....; // calculate positions here
  }
  return this._markersPositions;
}
```

2024-03-12 12:56 UTC, kirchet commented on src/views/pane/series-markers-pane-view.ts
> +		return 0;
This method doesn't use `this` so I suggest to move this logic to a function.

2024-03-14 20:32 UTC, kirchet commented on src/views/pane/series-markers-pane-view.ts
> +			});
Everything looks good except this `// eslint-disable-next-line @typescript-eslint/tslint/config`. I guess it's a formatting issue. Try to change the code to

```suggestion
			this._markersPositions = this._series.indexedMarkers().reduce(
				(acc: MarkerPositions, marker: InternalSeriesMarker<TimePointIndex>) => {
					if (!acc[marker.position]) {
						acc[marker.position] = true;
					}
					return acc;
				},
				{
					inBar: false,
					aboveBar: false,
					belowBar: false,
				}
			);
```

2024-03-15 10:18 UTC, kirchet commented on src/views/pane/series-markers-pane-view.ts
> +			});
Thanks

2024-03-15 10:45 UTC, kirchet commented
For some reason the pipeline step `install-deps` failed. @SlicedSilver can you take a look at this?

2024-03-15 11:55 UTC, SlicedSilver commented
> For some reason the pipeline step `install-deps` failed. @SlicedSilver can you take a look at this?

It appears to be an issue with downloading and installing chromium for puppeteer. https://app.circleci.com/pipelines/github/tradingview/lightweight-charts/2324/workflows/1f3fb2b3-814d-4e8d-b8d4-3346cf8a0bde/jobs/31071

We could try bump the puppeteer version to the latest but it is possible that memlab would also need to be bumped to a newer version. I'll experiment on a different branch.

2024-03-15 16:29 UTC, SlicedSilver commented
> @SlicedSilver also to update puppeteer we need to drop node 16, they dropped support for it in 22 major version

We are updating the node requirement in this different PR: https://github.com/tradingview/lightweight-charts/pull/1527
and there is also a task to update all the dependencies before v5 release (CLL-257)

2024-03-18 10:56 UTC, SlicedSilver approved these changes

2024-03-19 09:55 UTC, kirchet approved these changes

2024-03-19 11:12 UTC, merged