WIP Enable pane support
tradingview/lightweight-charts pull request #1557
Opened 2024-04-05 10:34 UTC by illetid

**Type of PR:** enhancement

**PR checklist:**

- [ ] Addresses an existing issue: fixes #50 
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**
Based on community implementation https://github.com/tradingview/lightweight-charts/pull/824

2024-04-09 15:01 UTC, kirchet requested changes

2024-04-09 15:08 UTC, kirchet commented on src/model/series.ts
>  		const targetPriceScaleId = options.priceScaleId;
If we need a new field then it should be included in `SeriesPartialOptionsInternal<T>`

This options can be useful only to move a series from one pane to another.
I would add a special method to do it instead

```TS
ISeriesAPi {
  ...
  moveToPane(paneIndex: number): void;
}
```

2024-04-10 12:03 UTC, illetid commented on src/gui/chart-widget.ts
> +		details: Point & PaneInfo | null,
it will work for click cases because we register them on the pane creation phase, but not for `_onPaneWidgetCrosshairMoved` because we register listener in `constructor` and we don't know about the pane  there, so pass paneIndex with coordinates looks like nice common solutions. But maybe I didn't get your idea correctly

2024-04-10 12:06 UTC, illetid commented on src/gui/pane-separator.ts
> +		this._chartWidget.adjustSize();
with `this._chartWidget.model().fullUpdate()` we have glitches when resizing panes via dragging pane separator. It works great with `adjustSize()` though. I'm not sure why, will investigate

2024-04-10 12:07 UTC, illetid commented on src/model/chart-model.ts
> +						(source as Series<SeriesType>).applyOptions({ pane: i - 1 });
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/7b747ff7dea8192a423a32b06b53b4a2d1acb1ea could you pls check if you had something like that in your mind?

2024-04-10 12:07 UTC, illetid commented on src/model/chart-model.ts
> +	private readonly _panesToIndex: Map<Pane, number> = new Map<Pane, number>();
removed, thanks

2024-04-10 12:07 UTC, illetid commented on src/model/series.ts
>  		const targetPriceScaleId = options.priceScaleId;
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/7b747ff7dea8192a423a32b06b53b4a2d1acb1ea could you pls check if you had something like that in your mind?

2024-04-10 12:07 UTC, illetid commented on src/api/ichart-api.ts
> +	swapPane(first: number, second: number): void;
renamed, thanks

2024-04-10 12:08 UTC, illetid commented on src/model/chart-model.ts
> +	panes: PanesOptions;
moved to layout options, thanks for the suggestion

2024-04-10 14:12 UTC, kirchet commented on src/model/series.ts
>  		const targetPriceScaleId = options.priceScaleId;
Yes, thanks

2024-04-10 14:18 UTC, kirchet commented on src/gui/chart-widget.ts
> +		details: Point & PaneInfo | null,
We can easely bind the proper value:

```TS
paneWidget.clicked().subscribe(this._onPaneWidgetClicked.bind(this, paneWidget), this);
```

2024-04-10 14:49 UTC, illetid commented on src/gui/chart-widget.ts
> +		details: Point & PaneInfo | null,
I tried to do that, but in the end, we call `_getMouseEventParamsImpl` for all cases: click, double click, and hover. And for click and double click, we can pass pane via the `bind,` but we can't do that for hover listener `this.model().crosshairMoved().subscribe(this._onPaneWidgetCrosshairMoved.bind(this), this);` on line 110.  I don't know what is the best solution for this case, maybe you have some ideas

2024-04-10 15:49 UTC, kirchet requested changes

2024-04-10 15:49 UTC, kirchet commented on src/model/chart-model.ts
> +				}
Probably we should first validate/modify index like `index = Math.max(0, Math.min(this._panes.length, index))`

2024-04-10 15:49 UTC, kirchet commented on src/model/series.ts
> +		this._paneIndex = paneIndex;
We don't need to store pane index in series and keep it in sync when we move series from pane to pane or remove some pane. We can calculate id dynamically

```TS
class ChartModel {
  ...
  public paneIndex(series: ISeries): number | null {
    for (let i = 0; i < this._panes.length; i += 1) {
      if (this._panes[i].contains(series)) {
        return i;
      }
    }
    return null;
  }
}
```

2024-04-10 15:56 UTC, illetid commented on src/gui/chart-widget.ts
> +		details: Point & PaneInfo | null,
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/ed08ef7fb1f5f948d4ce0cfd919fb544b24e8e35

2024-04-10 16:19 UTC, illetid commented on src/model/chart-model.ts
> +				}
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/6bdd22c8c7c6d35c9c4803704d4326287b74a218

2024-04-10 16:19 UTC, illetid commented on src/model/series.ts
> +		this._paneIndex = paneIndex;
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/6bdd22c8c7c6d35c9c4803704d4326287b74a218

2024-04-10 17:24 UTC, kirchet commented
Also take a look at horizontal crosshair line visibility, it should be painted on the active pane only. The same logic should be applied for crosshair price label as well.

![image](https://github.com/tradingview/lightweight-charts/assets/1572087/4fa1e359-187b-4609-9e83-c569f33c0225)

And for some reason vertical line is not painted on the first pane

2024-04-11 11:56 UTC, illetid commented on src/model/chart-model.ts
> +		}
thanks for the suggestion, fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/cc0421f9aa4016a98c343826e33c2aeecbddeb9f

2024-04-11 11:56 UTC, illetid commented on src/model/chart-model.ts
> +		});
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/cc0421f9aa4016a98c343826e33c2aeecbddeb9f

2024-04-11 11:57 UTC, illetid commented
> Also take a look at horizontal crosshair line visibility, it should be painted on the active pane only. The same logic should be applied for crosshair price label as well.
> 
> ![image](https://private-user-images.githubusercontent.com/1572087/321339362-4fa1e359-187b-4609-9e83-c569f33c0225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzY4MDYsIm5iZiI6MTcxMjgzNjUwNiwicGF0aCI6Ii8xNTcyMDg3LzMyMTMzOTM2Mi00ZmExZTM1OS0xODdiLTQ2MDktOWU4My1jNTY5ZjMzYzAyMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTE1NTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JkZGZhZTk5NWFiYjFkZjIyNzFiZWRlOTE0OGZjOGY4OWM0ZDUwYmU3OTRlNGNmYWRhMjYwNjZjZjFkZDBiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BMYFC5g3-NKU5n6T43b3QzNkGNh5b5ZDZbbDGalBwY4)
> 
> And for some reason vertical line is not painted on the first pane


thanks for spotting this one, fixed crosshair in https://github.com/tradingview/lightweight-charts/pull/1557/commits/5fc37ee4450b9db08174c048ed61b045e0d63677

2024-04-11 17:35 UTC, kirchet requested changes

2024-04-11 17:35 UTC, kirchet commented on src/model/chart-model.ts
> +	private _suppressSeriesMoving: boolean = false;
Seems that it's not used anymore

2024-04-11 17:35 UTC, kirchet commented on src/model/crosshair.ts
> +		}
Looks that these lines can be removed

2024-04-11 17:35 UTC, kirchet commented on src/model/crosshair.ts
> +		this._crosshairPaneViewCache.get(this._pane as Pane)?.update();
This line can be removed, we updated all views for each pane above

2024-04-11 18:56 UTC, illetid commented on src/model/crosshair.ts
> +		this._crosshairPaneViewCache.get(this._pane as Pane)?.update();
thanks, removed unused code in [7391663](https://github.com/tradingview/lightweight-charts/pull/1557/commits/7391663dc766c84f6b1b129f4663e990db4fb206)

2024-04-12 11:01 UTC, kirchet commented on src/gui/pane-separator.ts
> +		this._chartWidget.adjustSize();
Fixed in e612037c3effdd583901d4ef6e6f027be24f8dc0

2024-04-12 11:33 UTC, kirchet requested changes

2024-04-12 11:33 UTC, kirchet commented on src/gui/chart-widget.ts
> +		details: Point | null,
Let's rename it back to `point` here and in another places in this file

2024-04-12 11:33 UTC, kirchet commented on src/model/chart-model.ts
> +			this._invalidate(mask);
```suggestion
			this.fullUpdate();
```

2024-04-12 11:33 UTC, kirchet commented on src/model/pane.ts
> +		if (this._rightPriceScale.id() === DefaultPriceScaleId.Right && options.rightPriceScale) {
Why do we check additionaly for `this._rightPriceScale.id() === DefaultPriceScaleId.Right` but don't do the same for the left price scale?

2024-04-12 11:33 UTC, kirchet commented on src/views/pane/crosshair-marks-pane-view.ts
> +			.filter((entry: [IPriceDataSource, number]) => pane.dataSources().includes(entry[0]));
There is no need to get series from the whole chart, we should use series from the provided pane only

2024-04-12 11:33 UTC, kirchet commented on src/views/pane/crosshair-marks-pane-view.ts
> +	private _validated: Map<Pane, PaneRendererMarks[]> = new Map();
Instead of this we should create  `CrosshairMarksPaneView` for each pane.

2024-04-12 12:23 UTC, eugene-korobko commented on src/model/chart-model.ts
> +			paneIndex = Math.max(0, Math.min(this._panes.length, paneIndex));
It looks like we can just use `this._panes.length` here

Since this._panes.length - 1 <= paneIndex, Math.min(this._panes.length, paneIndex) is always equal to this._panes.length
And also paneIndex could not be negative

2024-04-12 13:24 UTC, karaevmaksim commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
How we can place legends for each pane without that?

2024-04-12 13:26 UTC, illetid commented on src/gui/chart-widget.ts
> +		details: Point | null,
changed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/f90efe5b0bdd61fbd3bc3f9eaeb15d02fd34c3b0

2024-04-12 13:28 UTC, illetid commented on src/views/pane/crosshair-marks-pane-view.ts
> +	private _validated: Map<Pane, PaneRendererMarks[]> = new Map();
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/cced5695984042f22399ae78514a26ef6437699d

2024-04-12 13:28 UTC, illetid commented on src/views/pane/crosshair-marks-pane-view.ts
> +			.filter((entry: [IPriceDataSource, number]) => pane.dataSources().includes(entry[0]));
thanks, fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/cced5695984042f22399ae78514a26ef6437699d

2024-04-12 13:30 UTC, illetid commented on src/model/pane.ts
> +		if (this._rightPriceScale.id() === DefaultPriceScaleId.Right && options.rightPriceScale) {
it was part of the original community implementation, forgot to cleanup, reverted this change, thanks

2024-04-12 13:37 UTC, illetid commented on src/model/chart-model.ts
> +			paneIndex = Math.max(0, Math.min(this._panes.length, paneIndex));
we use it to normalize user input in cases like if the user calls `chart.addLineSeries({}, 3);` but we have only one pane, instead of adding empty panes, we add only one new pane with this series, not sure if it is the best way to handle this, maybe we should add some assertions

2024-04-12 17:02 UTC, illetid commented on src/api/iseries-api.ts
> +	moveToPane(paneIndex: number): void;
could you pls check https://github.com/tradingview/lightweight-charts/pull/1557/commits/d9c4ab498ed84e56497d40ccb4c23a7a41c164a9 I've added Api to get pane/series on chart lvl and on PaneApi and SeriesApi to make it easier for user, but not sure is it okay?

2024-04-12 17:12 UTC, kirchet requested changes

2024-04-12 17:12 UTC, kirchet commented on src/model/crosshair.ts
> +		this._crosshairPaneViewCache.get(this._pane as Pane)?.update();
Added back again in https://github.com/tradingview/lightweight-charts/pull/1557/commits/cced5695984042f22399ae78514a26ef6437699d

2024-04-12 17:12 UTC, kirchet commented on src/views/pane/crosshair-marks-pane-view.ts
> +		const serieses = this._pane.dataSources() as ISeries<SeriesType>[];
Now a pane can contain only series, so let's rename `IPane.dataSources()` to `series():  ISeries<SeriesType>[]`

2024-04-12 17:14 UTC, kirchet commented on src/views/pane/crosshair-marks-pane-view.ts
> +		const serieses = this._pane.dataSources() as ISeries<SeriesType>[];
UPD: The same is applicable for `IPane.orderedSources()`

2024-04-12 17:24 UTC, kirchet commented on src/views/pane/crosshair-marks-pane-view.ts
> +		const serieses = this._pane.dataSources() as ISeries<SeriesType>[];
Or we need to add a type guard like `isSeries(source: IDataSource): source is ISeries<SeriesType>`

2024-04-15 08:46 UTC, illetid commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
removed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/ed8195b4695122c7ef0611cad025502b60ead31d

2024-04-15 08:58 UTC, illetid commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
@karaevmaksim you will be able to access HTML elements from the javascript or CSS, that API exposed just a `<tr>` element. you can query them with something like `document.querySelector(".tv-lightweight-charts table tr:nth-child(odd)`, note that we need to use `odd` to filter out pane separators

2024-04-15 09:35 UTC, illetid commented on src/views/pane/crosshair-marks-pane-view.ts
> +		const serieses = this._pane.dataSources() as ISeries<SeriesType>[];
added in https://github.com/tradingview/lightweight-charts/pull/1557/commits/5a4260f789f21506a2dda61252f4cec22dd9b226

2024-04-15 10:40 UTC, SlicedSilver commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
We already expose an API to get a reference to the element created by the library for the chart: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#chartelement

Yes, we can expect the developer to use a query selector on that element to find the pane elements but if it is not increasing the bundle size then I think we can expose this API for getting the pane element.

If we decide to rearrange panes via css instead of how they are defined in the DOM, or start adding more elements which aren't panes then a querySelector might not be so simple to write to find the nth Pane.

In general, it is a useful API method to have if you are writing plugins which require some UI rendered outside of the canvas (a legend might be a good example).

We can address some concerns about exposing these elements by adding more details to the documentation comment, such as 'storing references to these elements might result in a memory leak if the pane element is removed by the library... etc'

2024-04-15 10:48 UTC, eugene-korobko commented on src/api/iseries-api.ts
> +	moveToPane(paneIndex: number): void;
Yes, they look nice

2024-04-15 10:51 UTC, eugene-korobko commented on src/model/chart-model.ts
> +			paneIndex = Math.max(0, Math.min(this._panes.length, paneIndex));
Yes, I understand this, I mean we can use 

```
paneIndex = this._panes.length;
```
instead of 

```
paneIndex = Math.max(0, Math.min(this._panes.length, paneIndex));
```

Or we could remove `if` and keep `Math.min(this._panes.length, paneIndex)`, there is no sence to have both `if` and `min`

2024-04-15 10:55 UTC, eugene-korobko commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
I generally do not mind for exposiong DOM elements, however I believe API should be systemic to avoid breaking changes in future. 

Why don't to have `paneElement` in `paneAPI` like chart does? Why don't we have getters for scales and other elements?

2024-04-15 11:16 UTC, SlicedSilver commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
Getting into more philosophical discussions here, but as a user of the library I would prefer a known breaking change over an unknown breaking change. Using `querySelector` requires knowing how the library generates the internal dom (i.e knowing the internal logic which is subject to change). If we change how we do this then it will be breaking change for users who needed to use `querySelector` and it wouldn't be in our release notes.
For me, this is more likely then changing our internal code to not have an element for each pane but if we do then we mention it as a breaking change.

My personal opinion is that this would be useful (or at least 'nice') to include. It will be highly likely that we would want to add buttons to the pane for actions such as: remove pane, move pane, make pane fullscreen, ... which would appear on the top right of the pane (like on CL). I was expecting that we would release this as a Plugin because it would be such a common request but not required to be part of the 'core' library.

If we still don't want to add this method then a compromise could be to at least add an attribute to the element in the DOM so it is easy to query select such as `<div data-pane-index="2">...</div>`.

2024-04-15 11:24 UTC, illetid commented on src/model/chart-model.ts
> +			paneIndex = Math.max(0, Math.min(this._panes.length, paneIndex));
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/70f36d359cbd59c852267b17cdedc252df7a848b . I changed the signature of `_createSeries` to receive `pane` instance and removed that `Math.max` check from `createSeries` because we do it anyway in `createPane`

2024-04-15 11:26 UTC, kirchet commented on src/api/chart-api.ts
> +	}
It's either should be a method in `PaneApi` or this method should have an argument like `paneIndex: number`

I prefer the first option.

The same is for `getPaneBySeries`, probably we should move it to `SeriesApi.getPane(): IPaneApi`

cc @eugene-korobko

2024-04-15 11:30 UTC, illetid commented on src/api/chart-api.ts
> +	}
We have the `series()` method in `PaneApi`, which is a call of `getSeriesByPane` same we have `getPane` method  in SeriesApi, which call of `getPaneBySeries`

2024-04-16 07:17 UTC, eugene-korobko commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
ok, what about moving it to IPAneApi? 

IPaneAPI.getHTMLElement()

2024-04-16 09:49 UTC, kirchet commented on src/api/chart-api.ts
> +	}
I still think that moving these methods to `IPaneApi.getSeries()` and `ISeriesApi.getPane()` is a better option

2024-04-16 09:57 UTC, illetid commented on src/api/chart-api.ts
> +	}
we need to use `chartApi`'s `_seriesMap` and it is internal property, I don't think we should expose it, and I didn't figure out how we could get it without method duplication, maybe you have some ideas

2024-04-16 09:57 UTC, illetid commented on src/api/ichart-api.ts
> +	getPaneElements(): HTMLElement[];
added `IPaneAPI.getHTMLElement()`  in https://github.com/tradingview/lightweight-charts/pull/1557/commits/6af4122540fd859b46a05da50e191a739604b6c7 , thanks for suggestion

2024-04-16 10:29 UTC, illetid commented on src/api/chart-api.ts
> +	}
we have  `IPaneApi.getSeries()` and `ISeriesApi.getPane()` and they just call `ChartApi` methods because we need access to internal `_seriesMap` property, what do you think about this approach? @kirchet @SlicedSilver

2024-04-16 10:38 UTC, kirchet commented on src/api/chart-api.ts
> +	}
I don't see anything wrong/bad if we add a method like `ChartApi.getSeriesApi(series: ISeries): ISeriesApi`. But anyway we can work around it with a getter provided to `PaneApi` constructor.

```TS
export class PaneApi<HorzScaleItem> implements IPaneApi<HorzScaleItem> {
  ...
  private readonly _seriesApiGetter: (series: ISeries) => ISeriesApi;

  public constructor(
    chartApi: IChartApiBase<HorzScaleItem>,
    chartWidget: IChartWidgetBase,
    pane: Pane,
    seriesApiGetter: (series: ISeries) => ISeriesApi
) {
  this._seriesApiGetter = seriesApiGetter;
}
```

2024-04-16 11:31 UTC, illetid commented on src/api/chart-api.ts
> +	}
thanks for the suggestion, changed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/9c5b9f73a1c7bd3d39e54520a4078bc1cb217615

2024-04-17 13:29 UTC, SlicedSilver requested changes

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/chart-model.ts
> +
This implementation allows the use of a negative number.
`splice` supports the use of a negative number so if this is intended then it should be mentioned in the JSDoc comment on the API.

So `-2` would mean the second last pane in the array will be removed. 

We should either document this, or add an assert to restrict the numbers supplied.

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/chart-model.ts
> +		const maxPaneHeight = totalHeight - 30 * (this._panes.length - 1);
Don't use 30 but rather use the constant you defined elsewhere.

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/chart-model.ts
> +	}
```suggestion
	private _seriesPaneIndex(series: Series<SeriesType>): number {
		return this._panes.findIndex((pane: Pane) => pane.series().includes(series));
	}
```
Does it need to be public, and do we need to be able to return `null` if not found?
To me it only looks like it is used in `moveSeriesToPane()` and we don't check for null (only that it is different to the new index)

2024-04-17 13:29 UTC, SlicedSilver commented on src/gui/chart-widget.ts
> +	public adjustSize(): void {
Does this need to be public?

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/default-price-scale.ts
> +	Right = 'right'
Unneeded change?

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/pane.ts
> +	public series(): readonly Series<SeriesType>[] {
Could this be `ISeries` instead?

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/pane.ts
> +	public constructor(timeScale: ITimeScale, model: IChartModelBase, initialPaneIndex: number = 0) {
I think we can remove `initialPaneIndex` here

2024-04-17 13:29 UTC, SlicedSilver commented on src/model/series.ts
> -
[Minor] unneeded change?

2024-04-17 13:29 UTC, SlicedSilver commented on src/views/pane/crosshair-marks-pane-view.ts
> +		const serieses = this._pane.orderedSources() as ISeries<SeriesType>[];
Do we need the type assertion here? If possible it would be better to not use `as`

2024-04-17 13:29 UTC, SlicedSilver commented on src/views/pane/crosshair-pane-view.ts
> +		const pane = this._pane;
in this function we do the following:
```js
const pane = this._pane;
// ...
const crosshairOptions = pane.model().options().crosshair;
// ...
data.horzLine.visible = visible && this._source.horzLineVisible(this._pane);
```
Let's either use `this._pane` everywhere, or `pane` everywhere

2024-04-17 13:29 UTC, SlicedSilver commented on tests/e2e/coverage/test-cases/panes/options.js
> +	return [];
[Minor] Would be good if we tested the drag adjustment of the pane separator.

Only if it is easy. `tests/e2e/interactions/test-cases/markers/text-hit-test.js` is a similar-ish type of test case

2024-04-17 13:29 UTC, SlicedSilver commented on tests/e2e/helpers/perform-interactions.ts
> +	| 'paneSeparator';
👍

2024-04-17 14:44 UTC, illetid commented on src/api/options/layout-options-defaults.ts
> +		separatorColor: '#2B2B43',
I picked it to be the same as timeline borderColor, and `#E0E3EB` has a lack of contrast and looks like chart grid lines
<img width="833" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/15368332/efe85e39-48c0-4f7b-b0d1-01e470c57f9b">

2024-04-17 15:29 UTC, illetid commented on src/model/chart-model.ts
> +	moveSeriesToPane(series: Series<SeriesType>, newPaneIndex: number): void;
this method uses `series.applyOptions` and we don't have this method  in `ISeries` declaration

2024-04-17 16:12 UTC, illetid commented on src/api/ichart-api.ts
> +	panes(): IPaneApi<HorzScaleItem>[];
changed, thanks

2024-04-17 16:14 UTC, illetid commented on src/api/ichart-api.ts
> +	paneSize(paneIndex: number): PaneSize;
Changed tsdoc to specify the default parameter, but we can't have both optional parameter and default value

2024-04-17 16:16 UTC, illetid commented on src/gui/chart-widget.ts
> +		const pixelRatio = document.body.ownerDocument.defaultView?.devicePixelRatio || 1;
thanks, changed to `window`

2024-04-17 16:17 UTC, illetid commented on src/gui/pane-separator.ts
> +			this._handle.element.style.backgroundColor = 'hsla(225,8%,72%,.2)';
added configuration for the hover color, thanks

2024-04-17 16:17 UTC, illetid commented on src/gui/pane-separator.ts
> +		this._handle.element.style.backgroundColor = '';
removed background color change

2024-04-17 16:17 UTC, illetid commented on src/gui/pane-widget.ts
> +
forgot to delete before, removed now, thanks

2024-04-17 16:18 UTC, illetid commented on src/model/chart-model.ts
> +
added assertion, thanks

2024-04-17 16:19 UTC, illetid commented on src/model/chart-model.ts
> +		const maxPaneHeight = totalHeight - 30 * (this._panes.length - 1);
moved to constant, thanks

2024-04-17 16:20 UTC, illetid commented on src/gui/chart-widget.ts
> +	public adjustSize(): void {
this method was unused, removed it

2024-04-17 16:24 UTC, illetid commented on src/model/pane.ts
> +	public series(): readonly Series<SeriesType>[] {
unfortunately no, we use it in `moveSeriesToPane` and it works with `Series` not `ISeries` and it didn't compile

2024-04-17 16:24 UTC, illetid commented on src/model/pane.ts
> +	public constructor(timeScale: ITimeScale, model: IChartModelBase, initialPaneIndex: number = 0) {
removed

2024-04-17 16:25 UTC, illetid commented on src/views/pane/crosshair-marks-pane-view.ts
> +		const serieses = this._pane.orderedSources() as ISeries<SeriesType>[];
changed method to get series and removed `as`

2024-04-17 16:25 UTC, illetid commented on src/views/pane/crosshair-pane-view.ts
> +		const pane = this._pane;
fixed, thanks

2024-04-17 16:25 UTC, illetid commented on tests/e2e/coverage/test-cases/panes/options.js
> +	return [];
added drag test, thanks

2024-04-17 16:27 UTC, illetid commented on src/gui/chart-widget.ts
> +			: this.model().panes().indexOf(this.model().crosshairSource().pane() as Pane);
I cast it to `Pane` to avoid adding one more check if it is `null` because we check for `-1` after so it won't cause any issues

2024-04-18 10:22 UTC, kirchet commented
It's something wrong here 🙂

![image](https://github.com/tradingview/lightweight-charts/assets/1572087/3d678a77-d7ae-4f5b-ab0a-8f0dea6aa26d)

2024-04-18 10:30 UTC, SlicedSilver commented
> It's something wrong here 🙂
> 
> ![image](https://private-user-images.githubusercontent.com/1572087/323563772-3d678a77-d7ae-4f5b-ab0a-8f0dea6aa26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY0MTQsIm5iZiI6MTcxMzQzNjExNCwicGF0aCI6Ii8xNTcyMDg3LzMyMzU2Mzc3Mi0zZDY3OGE3Ny1kN2FlLTRmNWItYWIwYS04ZjBkZWE2YWEyNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTAyODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEwZWFhYjM3YWFkMmNiZWJlNGNhMjYxNGZkNTI5NGM3MmUxOGZkOWJkNWIxN2Q2OWU2OGRkMGRlNTFiYTA4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fhvVLm2haFcJskyjEaMvC5l6scs2Sw0G22N6D8P7xgo)

'QA' testing coming soon. 😅 Been focused on the API design review first.

Agree that we should only have a single TV attribution logo (on the bottom pane).

2024-04-18 21:18 UTC, SlicedSilver commented on src/gui/chart-widget.ts
> +			: this.model().panes().indexOf(this.model().crosshairSource().pane() as Pane);
If typescript is saying that the result could be `null` then perhaps it is better to use `ensureNotNull()`.

2024-04-18 21:18 UTC, SlicedSilver commented on src/model/pane.ts
> +	public series(): readonly Series<SeriesType>[] {
Is that not a sign that perhaps there has been a public method added to `Series` but not added to `ISeries`?

2024-04-18 21:22 UTC, SlicedSilver commented on src/api/ichart-api.ts
> +	paneSize(paneIndex: number): PaneSize;
At the `ichart-api` level it is possible to have it as an optional parameter, while the internal API has it specified with a default value.

2024-04-18 21:25 UTC, SlicedSilver commented on src/api/iseries-api.ts
> +	 */
The new wording is now
```
The index of the pane. Should be a number between 0 and the total number of panes + 1.
```

If you had 2 panes, then the above sentence implies that the following are valid: 0, 1, 2, 3.

So the sentence should probably be:
```
The index of the pane. Should be a number between 0 and the total number of panes.
```

2024-04-19 08:49 UTC, illetid commented on src/gui/chart-widget.ts
> +			: this.model().panes().indexOf(this.model().crosshairSource().pane() as Pane);
fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/9d3611d5dbfa11bba4bcce144a4215f88bbe458e

2024-04-22 11:32 UTC, illetid commented
> > It's something wrong here 🙂
> > ![image](https://private-user-images.githubusercontent.com/1572087/323563772-3d678a77-d7ae-4f5b-ab0a-8f0dea6aa26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY0MTQsIm5iZiI6MTcxMzQzNjExNCwicGF0aCI6Ii8xNTcyMDg3LzMyMzU2Mzc3Mi0zZDY3OGE3Ny1kN2FlLTRmNWItYWIwYS04ZjBkZWE2YWEyNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTAyODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEwZWFhYjM3YWFkMmNiZWJlNGNhMjYxNGZkNTI5NGM3MmUxOGZkOWJkNWIxN2Q2OWU2OGRkMGRlNTFiYTA4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fhvVLm2haFcJskyjEaMvC5l6scs2Sw0G22N6D8P7xgo)
> 
> 'QA' testing coming soon. 😅 Been focused on the API design review first.
> 
> Agree that we should only have a single TV attribution logo (on the bottom pane). Also the price label is different. Is it the exact same data? or is it randomised a bit?

fixed logo duplication in https://github.com/tradingview/lightweight-charts/pull/1557/commits/c391ec18accda43087f4bf3a345fe69a7b167f8e

2024-04-23 15:43 UTC, illetid commented on website/tutorials/how_to/panes.mdx
> +import UsageGuidePartial from "./_usage-guide-partial.mdx";
thanks, added your previous suggestions and also commited the `UsageGuidePartial` in https://github.com/tradingview/lightweight-charts/pull/1557/commits/aefd079808d60c390a077c1b0808e91c581750e3#diff-53cd3e1dfe2906463ae48d7fdbbf44441a4b0ee796cea74fa9b075a0e1b8200d.

2024-04-24 09:51 UTC, KatPierce commented on website/tutorials/how_to/panes.mdx
> +Lightweight Charts™ includes  [`PaneApi`](/docs/next/api/interfaces/IPaneApi) that allows you to control each pane. The API has methods to get information on the pane such as `getHeight()`, `paneInde
```suggestion
Lightweight Charts™ includes  [`PaneApi`](/docs/next/api/interfaces/IPaneApi) that allows you to control each pane. The API has methods to get information on the pane such as `getHeight()`, `paneIndex()`, and `getSeries()`. It also contains methods to adjust the pane parameters, for example `setHeight(height)` and `moveTo(paneIndex)`.
```

2024-04-24 09:51 UTC, KatPierce commented on website/tutorials/how_to/panes.mdx
> +To get the `PaneApi` instance for each pane, you need to call the `panes` method on the `ChartApi` instance.
```suggestion
To get a `PaneApi` instance for each pane, you need to call the `panes` method on the `ChartApi` instance.
```

2024-04-24 09:51 UTC, KatPierce commented on website/tutorials/how_to/_usage-guide-partial.mdx
> +- and that there is an html div element on the page with an `id` of `container`.
```suggestion
<strong>Before you use the code sample below, you should do the following::</strong>

-  Import `createChart`. Refer to [Getting Started](/docs#creating-a-chart) for more information.
-  Add an HTML div element with the `id` of the `container`.
```

2024-04-24 09:51 UTC, KatPierce commented on website/tutorials/how_to/panes.js
> +		// setting this to false will disable the resize of the panes by the user
I suppose that this line is missing in the code
`enableResize: false,`

2024-04-24 09:51 UTC, KatPierce commented on website/docs/panes.md
> +While the specific methods to manipulate panes are covered in the detailed [example](/tutorials/how_to/panes), it's important to note that Lightweight Charts provides an [API for pane management](/ap
Sorry, maybe my suggestion was vague. 
This part about manipulating panes was good, let's bring it back to a separate paragraph. So, it will be:

> ## Managing panes
> 
> While the specific methods to manipulate panes are covered in the detailed [example](/tutorials/how_to/panes), it's important to note that Lightweight Charts provides an [API for pane management](/api/interfaces/IPaneApi.md). This includes adding new panes, moving series between panes, adjusting pane height, and removing panes. The API ensures that developers have full control over the pane lifecycle and organization within their charts.

2024-04-24 09:51 UTC, KatPierce commented on website/docs/panes.md
> +
Let's remove the empty line between the first sentence and the next paragraph
```suggestion
```

2024-04-24 10:17 UTC, KatPierce approved these changes

2024-04-24 12:35 UTC, romfrancois commented on website/docs/panes.md
> +By default, Lightweight Charts has a single pane, however, you can add more panes to the chart to display different series in separate areas. For detailed examples and code snippets on how to impleme
```suggestion
By default, Lightweight Charts™ has a single pane, however, you can add more panes to the chart to display different series in separate areas. For detailed examples and code snippets on how to implement panes in your charts [see tutorial](/tutorials/how_to/panes).
```

Could you please add `™` next to all mention of `Lightweight Charts` ?

2024-04-24 14:46 UTC, illetid commented on website/docs/panes.md
> +By default, Lightweight Charts has a single pane, however, you can add more panes to the chart to display different series in separate areas. For detailed examples and code snippets on how to impleme
added, thanks

2024-04-25 13:39 UTC, romfrancois approved these changes

2024-04-25 15:22 UTC, kirchet requested changes

2024-04-25 15:22 UTC, kirchet commented on src/model/chart-model.ts
> +				}
1. This condition is always false
2. Let's rename the method to `getOrCreatePane`
3. Seems that we can make this method `private`

2024-04-26 09:44 UTC, kirchet approved these changes

2024-04-29 12:39 UTC, SlicedSilver commented
1. After an error of using `moveToPane(-1)` then you can no longer move the pane.
```js
// ...create a normal chart above...
volumeSeries = chart.addHistogramSeries(
    {
        priceFormat: {
            type: 'volume',
        },
    },
    1 // Pane index
);

volumeSeries.setData(generateLineData())

volumeSeries.moveToPane(2); // okay
volumeSeries.moveToPane(5); // okay
volumeSeries.moveToPane(-1); // error, but expected

volumeSeries.moveToPane(2); // error, but should work
```

---

2. Moving a series to a different price scale seems to also move the series to pane 0
```js
// ...create a normal chart above...
volumeSeries = chart.addHistogramSeries(
    {
        priceFormat: {
            type: 'volume',
        },
    },
    1 // Pane index
);

volumeSeries.setData(generateLineData())

// make left price scale visible
chart.applyOptions({leftPriceScale: {visible: true}})

// move volume series to left price scale
volumeSeries.applyOptions({priceScaleId: 'left'})

// !! now appears in pane 0

volumeSeries.moveToPane(1) // does nothing since it thinks it is in pane 1

volumeSeries.moveToPane(0) // hides empty pane 1
volumeSeries.moveToPane(1) // now the volume is back into the correct position
```

---

3. Using the above bug, it is possible to get an empty pane within the middle of the chart
```js
// ...create a normal chart above...
volumeSeries = chart.addHistogramSeries(
    {
        priceFormat: {
            type: 'volume',
        },
    },
    1 // Pane index
);

volumeSeries.setData(generateLineData())

// make left price scale visible
chart.applyOptions({leftPriceScale: {visible: true}})

// move volume series to left price scale
volumeSeries.applyOptions({priceScaleId: 'left'})

// !! now appears in pane 0

volumeSeries.moveToPane(2) // There is now an empty pane 1. Showing 3 panes
```

2024-04-29 12:41 UTC, SlicedSilver commented
[Minor] When dragging the pane separator, the time scale width can change. Maybe we would want to 'fix' the time scale width while dragging?

Let's only do this if it is easy, and lightweight to implement.

https://github.com/tradingview/lightweight-charts/assets/3482679/39e30ada-f9eb-4c0e-8339-68ef59572bbd

2024-04-30 10:35 UTC, illetid commented
> 1. After an error of using `moveToPane(-1)` then you can no longer move the pane.
> 
> ```js
> // ...create a normal chart above...
> volumeSeries = chart.addHistogramSeries(
>     {
>         priceFormat: {
>             type: 'volume',
>         },
>     },
>     1 // Pane index
> );
> 
> volumeSeries.setData(generateLineData())
> 
> volumeSeries.moveToPane(2); // okay
> volumeSeries.moveToPane(5); // okay
> volumeSeries.moveToPane(-1); // error, but expected
> 
> volumeSeries.moveToPane(2); // error, but should work
> ```
> 
> 2. Moving a series to a different price scale seems to also move the series to pane 0
> 
> ```js
> // ...create a normal chart above...
> volumeSeries = chart.addHistogramSeries(
>     {
>         priceFormat: {
>             type: 'volume',
>         },
>     },
>     1 // Pane index
> );
> 
> volumeSeries.setData(generateLineData())
> 
> // make left price scale visible
> chart.applyOptions({leftPriceScale: {visible: true}})
> 
> // move volume series to left price scale
> volumeSeries.applyOptions({priceScaleId: 'left'})
> 
> // !! now appears in pane 0
> 
> volumeSeries.moveToPane(1) // does nothing since it thinks it is in pane 1
> 
> volumeSeries.moveToPane(0) // hides empty pane 1
> volumeSeries.moveToPane(1) // now the volume is back into the correct position
> ```
> 
> 3. Using the above bug, it is possible to get an empty pane within the middle of the chart
> 
> ```js
> // ...create a normal chart above...
> volumeSeries = chart.addHistogramSeries(
>     {
>         priceFormat: {
>             type: 'volume',
>         },
>     },
>     1 // Pane index
> );
> 
> volumeSeries.setData(generateLineData())
> 
> // make left price scale visible
> chart.applyOptions({leftPriceScale: {visible: true}})
> 
> // move volume series to left price scale
> volumeSeries.applyOptions({priceScaleId: 'left'})
> 
> // !! now appears in pane 0
> 
> volumeSeries.moveToPane(2) // There is now an empty pane 1. Showing 3 panes
> ```

1. we are throwing an error and a developer who uses the library should handle the error
2. and 3 fixed in https://github.com/tradingview/lightweight-charts/pull/1557/commits/745e4bfac02cf29d62fa9bff43f962a4c79b954d

2024-04-30 10:37 UTC, illetid commented
> [Minor] When dragging the pane separator, the time scale width can change. Maybe we would want to 'fix' the time scale width while dragging?
> 
> Let's only do this if it is easy, and lightweight to implement.
> 
>  time-scale-width-changing.mov

@SlicedSilver could we move this to future improvements

2024-05-07 08:31 UTC, SlicedSilver approved these changes

2024-05-08 13:39 UTC, merged

2024-06-09 10:35 UTC, SigmaU commented
can't express how much I am waiting for this feature, guys! So grateful for everyones work ❤️

2024-12-25 15:54 UTC, vishnuc commented
I am excited for this feature , love you guys for this work :)

2025-01-27 07:35 UTC, hems commented
Can't wait for this : D

has anyone toyed around with doing a MACD panel ? : D

2025-01-27 07:36 UTC, vishnuc commented
I will be adding 50+ indicators to my project , once v5 is released , macd is one