make series tree-shakable
tradingview/lightweight-charts pull request #1714
Opened 2024-10-23 16:37 UTC by illetid

**Type of PR:** 

**PR checklist:**

- [ ] Addresses an existing issue: fixes #
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**

**Is there anything you'd like reviewers to focus on?**

2024-11-05 14:01 UTC, SlicedSilver requested changes

2024-11-05 14:01 UTC, SlicedSilver commented on src/api/ichart-api.ts
> +	addSeries<
This also needs a JSDoc comment string. This might work:
```
// eslint-disable-next-line tsdoc/syntax
/** @inheritdoc */
```

However I think it is better to keep `addCustomSeries` which internally can do the `createCustomSeries` for you so you don't need to write this:
```
const series = chart.addSeries(createCustomSeries(customSeriesView), { whiskerColor: 'string' });
```
but can use the old syntax of:
```
const series = chart.addCustomSeries(customSeriesView, { whiskerColor: 'string' });
```

2024-11-05 14:16 UTC, illetid commented on src/gui/chart-widget.ts
> +}
I switched to the `in` operator to prevent `Series` from being bundled into `createChart` because  using `instanceof` added it to the bundle. But now we have `Series` bundled anyway, so it makes no sense to use `in`. Thanks for spotting this

2024-11-06 09:15 UTC, illetid commented on src/model/series/area-pane-view.ts
> +import { Series } from '../../model/series';
revert `ISeries` in all places

2024-11-06 09:21 UTC, illetid commented on src/index.ts
> +export { histogramSeries as HistogramSeries } from './model/series/histogram-series';
from my perspective, we use this to instantiate series, and for users, it will be a thing to create series like a class, like they still need to do `chart.addSeries(series)`  they can just use this imported series right away, so pascal case seems more appropriate, but I don't have strong opinion about this

2024-11-06 09:21 UTC, illetid commented on src/model/magnet.ts
> +			((ds: IPriceDataSource) => ('seriesType' in (ds as unknown as any))) as (ds: IPriceDataSource) => ds is ISeries<SeriesType>);
reverted to `instance of`

2024-11-06 09:22 UTC, illetid commented on src/model/series.ts
> +		if (this._seriesType === 'Area' || this._seriesType === 'Line' || this._seriesType === 'Baseline') {
thanks for suggestion

2024-11-06 09:23 UTC, illetid commented on src/model/series.ts
> +	public override priceAxisViews(pane: unknown, priceScale: PriceScale): readonly IPriceAxisView[] {
reverted to `Pane`

2024-11-06 09:24 UTC, illetid commented on src/api/ichart-api.ts
> +	addSeries<
reverted `addCustomSeries` it added 200b to the bundle, but it totally makes sense to keep it

2024-11-06 15:51 UTC, SlicedSilver reviewed
In principle this looks good and we can proceed with a PR to merge the updated tests and documentation into this branch.

Once that PR is merged into this branch then we can add approval to this PR.

2024-11-06 15:51 UTC, SlicedSilver commented on src/model/series/series-def.ts
> +	readonly customPaneView?: ICustomSeriesPaneView<unknown>;
Is this only used for Custom Series? and If so is a `SeriesDefinition` of this type ever accessible?
My assumption is that since we moved `createCustomSeries` login inside of `addCustomSeries` that we could use a `InternalSeriesDefinition` for defining the `customPaneView`. Therefore this doesn't need to be part of the public API

2024-11-06 16:37 UTC, illetid commented on src/model/series/series-def.ts
> +	readonly customPaneView?: ICustomSeriesPaneView<unknown>;
👍 moved it into the internal interface, thanks

2024-11-13 09:38 UTC, SlicedSilver approved these changes

2024-11-13 15:23 UTC, merged