bugfix #549. Correct time scale behavior on setData
tradingview/lightweight-charts pull request #555
Opened 2020-08-28 09:36 UTC by beholderrk

**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #549
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Correct time scale behavior on setData. The time scale doesn't shift when data added to the left.

![2020-08-28_12-31-52](https://user-images.githubusercontent.com/841755/91546215-c6b6fa00-e92a-11ea-9411-ec929a33dfac.gif)

2020-09-07 09:15 UTC, timocov requested changes
sorry for late reply!

The PR looks good for me, thank for your time and work. Just some naming comments here.

2020-09-07 09:15 UTC, timocov commented on src/model/chart-model.ts
> +			const isDataAdded = newBaseIndex > currentBaseIndex;
I guess that `newBaseIndex > currentBaseIndex` doesn't really mean that "data was added". base index - it's a term to show the latest _real_ bar across all series on the chart (because of whitespaces, where timescale might have data additional data from the right, but no series has data there).

Thus, I think it's something like "added new bars from the right" or so (but actually this also doesn't mean that the data was added to the right though...)

2020-09-07 09:15 UTC, timocov commented on src/model/chart-model.ts
> +			const isVisibleRangeFilled = !isLastSeriesBarVisible && !isFirstSeriesBarVisible;
Maybe we need to call it something like `areDataEndsVisible`? @Nipheris can you please take a look here?

2020-09-07 09:15 UTC, timocov commented on src/model/chart-model.ts
> +			const isDataAdded = newBaseIndex > currentBaseIndex;
Or maybe we can just "inline" it to the `if` statement below (like it was previously)?..

2020-09-07 09:15 UTC, timocov commented on tests/e2e/graphics/test-cases/time-scale/add-data-to-right.js
> +	data = [...data, ...generateData(3, (data[data.length - 1].time + 24 * 60 * 60) * 1000)];
can we extract `24 * 60 * 60` to a variable?

2020-09-07 09:15 UTC, timocov commented on tests/e2e/graphics/test-cases/time-scale/add-data-to-right.js
> +	newRange = timeScale.getVisibleLogicalRange();
maybe we need to rename it to `newLogicalRange` to avoid confusing with `newTimeRange`?

2020-09-08 18:46 UTC, beholderrk commented on src/model/chart-model.ts
> +			const isFirstTimeChanged = oldFirstTime.timestamp > newFirstTime.timestamp;
> And add check that the old oldFirstTime.timestamp exist on the timescale

Sorry, not sure that I understood.
```suggestion
			const isDataAddedToLeft = oldFirstTime.timestamp > newFirstTime.timestamp && visibleBars.contains(???);
```

2020-09-08 18:46 UTC, beholderrk commented on src/model/chart-model.ts
> +			const isVisibleRangeFilled = !isLastSeriesBarVisible && !isFirstSeriesBarVisible;
`areDataEndsVisible` means like letf end of end and right end of data visible inside current timescale? 
```suggestion
			const areDataEndsVisible = isLastSeriesBarVisible && isFirstSeriesBarVisible;
```
But we need shift timescale when all ends of data out of timescale and bars added to right side of data.
Expression like this `if (isDataAddedToRight && !areDataEndsVisible )` will perform the shift when the right edge is visible, which we don't need.

May be `areDataEndsInvisible`?

2020-09-08 18:52 UTC, beholderrk commented on src/model/chart-model.ts
> +			const isDataAdded = newBaseIndex > currentBaseIndex;
Ok. I can also suggest "inline" it to the `isDataAddedToRight`
```suggestion
			const isDataAddedToRight = newBaseIndex > currentBaseIndex && !isDataAddedToLeft;
```

2020-09-08 18:53 UTC, beholderrk commented on tests/e2e/graphics/test-cases/time-scale/add-data-to-right.js
> +	data = [...data, ...generateData(3, (data[data.length - 1].time + 24 * 60 * 60) * 1000)];
ok

2020-09-08 18:53 UTC, beholderrk commented on tests/e2e/graphics/test-cases/time-scale/add-data-to-right.js
> +	newRange = timeScale.getVisibleLogicalRange();
ok

2020-09-10 16:55 UTC, timocov commented on src/model/chart-model.ts
> +			const isFirstTimeChanged = oldFirstTime.timestamp > newFirstTime.timestamp;
I think we need to use `timeScale.timeToIndex(oldFirstTime) !== null` - it returns index of the point inside time scale points. We don't need to check that old point was in the visible range (we check it right above).

2020-09-10 16:55 UTC, timocov commented on src/model/chart-model.ts
> +			const isDataAdded = newBaseIndex > currentBaseIndex;
Why it's so `&& !isDataAddedToLeft`? 🙂 I think that we can add from both side at the same time.

2020-09-10 16:55 UTC, timocov commented on src/model/chart-model.ts
> +			const isVisibleRangeFilled = !isLastSeriesBarVisible && !isFirstSeriesBarVisible;
> May be areDataEndsInvisible?

Yeah, I think it was typo, I'm sorry 😂 In terms of "data ends are visible" I guess we need to add _any_ there (`IsAnyDataEndVisible`) and make check "negative"

2020-09-18 09:10 UTC, beholderrk commented
![LCWXxQmLr2](https://user-images.githubusercontent.com/841755/93579981-d9f83b00-f9a7-11ea-918b-8147c5acc7c3.gif)
New tests with 2 series and whitespaces

2020-09-19 15:33 UTC, nalepae commented
What can be done to help this Pull Request to be merged?

Thanks a lot @beholderrk for your work!

2020-09-21 08:19 UTC, timocov approved these changes

2020-09-21 08:21 UTC, merged

2020-09-21 10:05 UTC, nalepae commented
@timocov perfect, thank you very much !

Do you know when the next official release is scheduled ?

2020-09-21 11:55 UTC, timocov commented
@nalepae we have to finish [3.2 milestone](https://github.com/tradingview/lightweight-charts/milestone/11), I hope it will be within couple of weeks (2-3).