Add api to show hide series without removing it #471
tradingview/lightweight-charts pull request #581
Opened 2020-09-21 14:24 UTC by olegchernenko

**Type of PR:** 

**PR checklist:**

- [ ] Addresses an existing issue: fixes #471
- [ ] Includes tests +
- [ ] Documentation update +

**Overview of change:**

**Is there anything you'd like reviewers to focus on?**

2020-09-21 15:01 UTC, timocov commented on src/views/pane/series-markers-pane-view.ts
> +		this._data.visible = this._series.options().visible;
why do we need to save it in data?

2020-09-21 15:01 UTC, timocov commented on src/views/pane/line-pane-view.ts
> +			visible: lineStyleProps.visible,
why do we need to add it to renderer options? I guess it's the last guy who should know about that

2020-09-21 15:01 UTC, timocov commented on src/views/pane/histogram-pane-view.ts
> +		this._histogramData.visible = this._series.options().visible;
the same

2020-09-22 08:12 UTC, timocov commented on docs/series-basics.md
> +By default, created series is visible. You can change its visibility using `SeriesApi.applyOptions`:
```suggestion
By default, all created series are visible. You can change the visibility using `applyOptions` method:
```

2020-09-22 08:12 UTC, timocov commented on docs/series-basics.md
> +When you hide a series - price line, base line, price labels and markers of series will also be hidden.
```suggestion
If the series is hidden - everything including its price lines, base line, price labels and markers will be hidden as well.
```

2020-09-22 08:12 UTC, timocov commented on docs/series-basics.md
> +```
```suggestion
Note that hiding the series is not equivalent to deleting it - hiding does not affect the time scale at all in opposite of deleting, when the time scale might be changed (some points might be deleted).
```

2020-09-22 08:27 UTC, ezhukovskiy requested changes

2020-09-22 08:27 UTC, ezhukovskiy commented on docs/series-basics.md
> +|`priceLineVisible`|`boolean`|`true`|If true, a series' price line is displayed on a chart if a series is visible|
```suggestion
|`priceLineVisible`|`boolean`|`true`|If true, a series' price line is displayed on a chart if the series is visible|
```

2020-09-22 08:27 UTC, ezhukovskiy commented on docs/series-basics.md
> +|`lastValueVisible`|`boolean`|`true`|If true, the label with the current price is displayed on the price scale if a series is visible|
```suggestion
|`lastValueVisible`|`boolean`|`true`|If true, the label with the current price is displayed on the price scale if the series is visible|
```

2020-09-22 08:27 UTC, ezhukovskiy commented on docs/series-basics.md
> +|`baseLineVisible`|`boolean`|`true`|If true, a series' base line is displayed on a chart if a series is visible|
```suggestion
|`baseLineVisible`|`boolean`|`true`|If true, a series' base line is displayed on a chart if the series is visible|
```

2020-09-22 08:52 UTC, timocov approved these changes

2020-09-22 09:24 UTC, timocov commented
It seems that magnet doesn't respect `visible` option (perhaps something else too?).

2020-09-22 11:37 UTC, timocov approved these changes

2020-09-22 11:37 UTC, merged