71: Use observer for auto resizing and hide "% 2" magic with a strategy
tradingview/lightweight-charts pull request #599
Opened 2020-10-23 13:27 UTC by eugene-korobko

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #71
- [ ] Includes tests
- [x] Documentation update

**Overview of change:**
- Added an option `useObserver` that makes the chart resizing automatically to fill parent's client area
- Extracted magic with keeping sizes odd to separate module and encapsulate with interface

**Is there anything you'd like reviewers to focus on?**

One graphic test has been broken because we start applying "odd magic" to explicitly defined sizes

2020-10-26 10:54 UTC, timocov requested changes

2020-10-26 10:54 UTC, timocov commented on src/model/chart-model.ts
> +	useObserver: boolean;
I'm not sure that `useObserver` is good name for handling resize. Maybe something like `autosize` or `handleResize`?

2020-10-26 10:54 UTC, timocov commented on src/model/chart-model.ts
> +	 * */
```suggestion
	 * Use ResizeObserver to handle container's resize to resize a chart automatically.
	 * Note that the library WON'T ADD own polyfill for `ResizeObserver` if it doesn't exist in the global scope. So you have to be sure that you enable this option only if a browser supports it or you provide a polyfill instead. Otherwise, a warn message will be printed and no handling resize will be applied.
	 **/
```

Maybe something like that?

2020-10-26 10:54 UTC, timocov commented on src/model/chart-model.ts
> +	 * */
Probably we need to update docs as well accordingly.

2020-10-26 10:54 UTC, timocov commented on src/gui/chart-widget.ts
> +		if (options.useObserver) {
What's about enabling this option on-the-fly? I guess it might be a trick, for instance if you'd like to load polyfills async and then handle resize events.

2020-10-26 10:54 UTC, timocov commented on src/gui/chart-widget.ts
> +				warn('Options contains "useObserver" flag, but the browser does not support this');
> the browser does not support this

I think we need to write a bit more about that. Doesn't support what?

2020-10-26 10:54 UTC, timocov commented on src/gui/chart-widget.ts
> +					if (!containerEntry || !containerEntry.devicePixelContentBoxSize) {
`containerEntry.devicePixelContentBoxSize` Do we need to check it here, even if we don't use it anywhere?

2020-10-26 10:54 UTC, timocov commented on src/gui/chart-widget.ts
> +			let size = new Size(this._options.width, this._options.height);
do we actually need to create this `Size` variable? Can't we use 2 `number` variables? 🤔

2020-10-26 10:54 UTC, timocov commented on src/gui/chart-widget.ts
> +			// or after but with adjustSize to properly update time scale
is it comment important while using `ResizeObserver`? Will a `callback` be called async?

2020-10-26 10:54 UTC, timocov commented on src/gui/internal-layout-sizes-hints.ts
> +export interface InternalLayoutSizeHints {
What does "internal" here mean? is it inner? or something else?

2020-10-26 10:54 UTC, timocov commented on src/gui/internal-layout-sizes-hints.ts
> +export class InternalLayoutSizeHintsKeepIriginal implements InternalLayoutSizeHints {
Is it used anywhere?

2020-10-26 16:46 UTC, eugene-korobko commented on src/model/chart-model.ts
> +	useObserver: boolean;
fitContent?

2020-10-26 16:48 UTC, timocov commented on src/model/chart-model.ts
> +	useObserver: boolean;
Nah, we already have that (method, but anyway) 😂 I think we might to look at others libraries, probably they already have this.

2020-10-26 16:56 UTC, eugene-korobko commented on src/gui/chart-widget.ts
> +			// or after but with adjustSize to properly update time scale
Yes, I think so. Call from observer callback is the same as external resize call

2020-10-26 16:57 UTC, eugene-korobko commented on src/gui/internal-layout-sizes-hints.ts
> +export interface InternalLayoutSizeHints {
This means this hints relate to internal chart layout - panes/scales/etc

2020-10-26 16:58 UTC, eugene-korobko commented on src/gui/internal-layout-sizes-hints.ts
> +export class InternalLayoutSizeHintsKeepIriginal implements InternalLayoutSizeHints {
no, it is just to allow easy disabling of %2 magic...
And I have a Typo here...

2020-10-27 07:31 UTC, timocov commented on src/gui/internal-layout-sizes-hints.ts
> +export class InternalLayoutSizeHintsKeepIriginal implements InternalLayoutSizeHints {
> no, it is just to allow easy disabling of %2 magic...

easy for whom? if it isn't used anywhere, it looks like deadcode, which will be removed from the bundle and you can't access it anyway (or even apply it somehow) 🤔

2020-10-27 07:32 UTC, timocov commented on src/gui/chart-widget.ts
> +			// or after but with adjustSize to properly update time scale
Don't we need to do a first resize in the widget constructor to have an initial size? I guess we should test it

2020-11-10 08:00 UTC, eugene-korobko commented on src/model/chart-model.ts
> +	useObserver: boolean;
Well, will rename to autoSize
If anyboydy has better name - speak now or forever hold your peace )

2020-11-10 08:53 UTC, eugene-korobko commented on src/gui/chart-widget.ts
> +			// or after but with adjustSize to properly update time scale
Yes.
ResizeObserver fires the first event immediately not for all the cases, so we have to set initial size with both cases

2020-11-10 08:55 UTC, eugene-korobko commented on src/gui/internal-layout-sizes-hints.ts
> +export class InternalLayoutSizeHintsKeepIriginal implements InternalLayoutSizeHints {
ok

2020-11-12 09:55 UTC, timocov requested changes
It seems there is some typos here

2020-11-12 09:55 UTC, timocov commented on docs/customization.md
> +    useObserver: true,
```suggestion
### Auto Size

Setting `autoSize` flag to `true` makes chart monitoring container and changing its size on every container resize.

This feature requires [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) class to be available in the global scope.

Note that calling code is responsible for providing a polyfill if required. If the global scope does not have `ResizeObserver`, a warning will appear and the flag will be ignored.

Please pay your attention that `autoSize` option and explicit sizes options `width` and `height` conflict one with others.

If you specify `autoSize` flag, `width` and `height` options will be ignored in common case and could only be used as fallback if using `ResizeObserver` has failed.

The flag `autoSize` could also be set with and unset with `applyOptions` function.

```js
const chart = LightweightCharts.createChart(document.body, {
    autoSize: true,
```

2020-11-12 09:55 UTC, timocov commented on src/gui/chart-widget.ts
> +	// replace InternalLayoutSizeHintsKeepOdd with InternalLayoutSizeHintsKeepOriginal to turn "odd magic" off
```suggestion
```

2020-11-12 09:55 UTC, timocov commented on src/gui/chart-widget.ts
> +		if (options.autoSize === false && this._observer) {
```suggestion
		if (options.autoSize && this._observer === null) {
			// installing observer will override resize if successful
			this._installObserver();
		}

		if (!options.autoSize && this._observer !== null) {
```

2020-11-12 09:55 UTC, timocov commented on src/gui/chart-widget.ts
>  		this.resize(width, height);
Shouldn't explicit resize disable autoSize?

2020-11-12 09:55 UTC, timocov commented on src/model/chart-model.ts
> +	 * If the global scope does not contain `ResizeObserver` object, a warning will appear the the flag will be ignored
```suggestion
	 * Setting this flag to `true` makes chart monitoring container and changing its size on every container resize.
	 * This feature requires [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) class to be available in the global scope.
	 * Note that calling code is responsible for providing a polyfill if required. If the global scope does not have `ResizeObserver`, a warning will appear and the flag will be ignored.
	 * Please pay your attention that `autoSize` option and explicit sizes options `width` and `height` conflict one with others.
	 * If you specify `autoSize` flag, `width` and `height` options will be ignored in common case and could only be used as fallback if using `ResizeObserver` has failed.
	 * The flag `autoSize` could also be set with and unset with `applyOptions` function.
```

_(or whatever will be in the docs)_

2020-11-12 09:55 UTC, timocov commented on tests/e2e/graphics/test-cases/initial-options/use-observer.js
> +		const chart = LightweightCharts.createChart(box, { useObserver: true, ...config });
```suggestion
		const chart = LightweightCharts.createChart(box, { autoSize: true, ...config });
```

2021-02-17 08:39 UTC, eugene-korobko commented on src/gui/chart-widget.ts
>  		this.resize(width, height);
probably yes, I've changed the logic a bit

2021-03-16 14:20 UTC, adgower commented
I pulled this branch ran npm install then npm run build:prod I could not get autoSize to work? Any tips? @eugene-korobko

2021-03-16 14:28 UTC, adgower commented
@eugene-korobko This works great!

2023-01-10 19:31 UTC, SlicedSilver commented
It is expected that the graphics tests will have a single failing test for `use-observer` as this is a new test specific for this feature.

2023-01-10 19:35 UTC, SlicedSilver commented
@eugene-korobko I've made a few changes so that this PR could be merged. Could you please review if you are happy with the changes.
@Nipheris This PR makes some minor changes to the `% 2` magic code. Could you please check if you are happy with these changes as a temporary measure until we can implement `fancy-canvas` perfectly.

2023-01-17 18:12 UTC, romfrancois reviewed
Very minor typos

2023-01-17 18:12 UTC, romfrancois commented on src/model/chart-model.ts
> +	 * Setting this flag to `true` will make the chart watch the chart container's size and automatically resize the chart to fit it's container whenever the size changes.
typo - it's container => its container

2023-01-17 18:12 UTC, romfrancois commented on src/model/chart-model.ts
> +	 * Please pay your attention that `autoSize` option and explicit sizes options `width` and `height` don't conflict with one another.
~~your~~

2023-01-17 18:12 UTC, romfrancois commented on src/gui/internal-layout-sizes-hints.ts
> +// For chart widget we decreases because we must be inside container.
decrease~~s~~

2023-01-17 18:17 UTC, SlicedSilver commented
@romfrancois Fixed the typos 👍

2023-01-17 18:22 UTC, romfrancois approved these changes

2023-01-17 18:34 UTC, merged