597: Fixed drawing single-pointed
tradingview/lightweight-charts pull request #603
Opened 2020-10-26 13:18 UTC by eugene-korobko

**Type of PR:** 

**PR checklist:**

- [x] Addresses an existing issue: fixes #597
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**
Processed special case - 1 bar - while drawing line or area

2020-11-12 09:39 UTC, timocov commented on src/renderers/line-renderer.ts
> +		if (this._data.items.length === 1) {
I think it'd be better to add a test case where data has more than 1 item, but visible range is for 1 point:

- 2 series
- the first one has data items at 0 and 2 time
- the second one has data item at 1 time

2 test cases:
- set visible range from 0 to 1
- set visible range from 1 to 2

2020-11-12 09:40 UTC, timocov requested changes
See review comment

2020-11-13 14:28 UTC, eugene-korobko commented on src/renderers/line-renderer.ts
> +		if (this._data.items.length === 1) {
Added three testcases:
The only visible point is the first bar
The only visible point is the last bar
There is no visible bars, however there are bars before and after the visible range

All three cases for both line and area.

These tests are green now and the picture is correct. So the condition to  compare data items length, not visible ones, is correct

2020-11-13 14:39 UTC, timocov approved these changes

2020-11-13 14:39 UTC, merged