606: Update scales design
tradingview/lightweight-charts pull request #607
Opened 2020-10-29 08:54 UTC by eugene-korobko

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #606
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**
Changed scales look & feel according to the new design

2022-05-20 14:06 UTC, kirchet commented on src/helpers/make-font.ts
> +
This function should be removed, cause it does wrong calculations

2022-05-20 14:19 UTC, kirchet commented on src/renderers/time-axis-view-renderer.ts
> +		const yText = y2 - rendererOptions.baselineOffset - rendererOptions.paddingBottom + rendererOptions.labelBottomOffset;
We should take into account `yMidCorrection` for some constant text

```
const textYCorrection = rendererOptions.widthCache.yMidCorrection(ctx, 'Apr0');
```

2022-05-20 14:29 UTC, kirchet commented on src/views/price-axis/price-axis-view.ts
> -		this._paneRendererData.tickVisible = this._paneRendererData.tickVisible && priceScale.options().ticksVisible;
I'm not sure tha we should change current behaviour here because it's a breaking change
https://github.com/tradingview/lightweight-charts/blob/405276e2b3e21e0e7af70093c8fb18d0841ab3c6/src/model/price-scale.ts#L164-L169

Ticks should be visible if this option is enabled. Maybe we should just change the default value to `false`.

The same is for time axis ticks
https://github.com/tradingview/lightweight-charts/blob/405276e2b3e21e0e7af70093c8fb18d0841ab3c6/src/model/time-scale.ts#L199-L204

2022-05-20 14:36 UTC, kirchet commented on src/views/price-axis/price-axis-view.ts
> -		this._paneRendererData.tickVisible = this._paneRendererData.tickVisible && priceScale.options().ticksVisible;
If we'll change default values we should invert the corresponding test cases (see `do-not-draw-price-ticks.js`, `do-not-draw-time-ticks`) and add a note about these changes to `from-v3-to-v4.md`

2022-05-23 07:27 UTC, eugene-korobko commented on src/views/price-axis/price-axis-view.ts
> -		this._paneRendererData.tickVisible = this._paneRendererData.tickVisible && priceScale.options().ticksVisible;
Well, after discussion I've reverted this change. Ticks work as before with the only change - ticksVisible option is off by default. Updated `from-v-to-v4.md`

2022-05-23 12:52 UTC, kirchet commented on src/renderers/price-axis-view-renderer.ts
> +		console.log(`text: ${text} width: ${textWidth}`);
Did you forget to remove it?

2022-05-24 11:54 UTC, kirchet commented
* Also we need to change the default value to `false` [here](https://github.com/tradingview/lightweight-charts/blob/74c985d2ecd97083ac12e8fa19ee2bd26b816a86/src/api/options/time-scale-options-defaults.ts#L17). No breaking change notes required because it's a new option
* Size limit tests failed
* The test cases `do-not-draw-price-ticks.js`, `do-not-draw-time-ticks.js`, `apply-do-not-draw-price-ticks.js` should be inverted

2022-05-24 18:13 UTC, kirchet requested changes

2022-05-24 18:13 UTC, kirchet commented on src/api/options/time-scale-options-defaults.ts
> +	ticksVisible: false,
Also we need to change the corresponding comments [here](https://github.com/tradingview/lightweight-charts/blob/37a80baf8cadeaf803f8462ed20018b15ca8df12/src/model/time-scale.ts#L202) and [here](https://github.com/tradingview/lightweight-charts/blob/37a80baf8cadeaf803f8462ed20018b15ca8df12/src/model/price-scale.ts#L167)

2022-05-24 18:13 UTC, kirchet commented on tests/e2e/graphics/test-cases/initial-options/draw-time-ticks.js
> +			ticksVisible: true,
I think we should also change the names of these files
* `draw-time-ticks.js` => `do-not-draw-time-ticks.js`
* `draw-price-ticks.js` => `do-not-draw-price-ticks.js` 
* `apply-do-not-draw-price-ticks.js` => `apply-draw-price-ticks.js`

2022-05-25 14:01 UTC, kirchet commented on tests/e2e/graphics/test-cases/initial-options/draw-time-ticks.js
> +			ticksVisible: true,
Ah sorry, my bad, missed it

2022-05-27 11:18 UTC, kirchet commented on .size-limit.js
> +		limit: '44323 B',
Why did you change it from kilobytes to bytes?

2022-06-02 13:40 UTC, kirchet approved these changes

2022-06-15 13:49 UTC, kirchet submitted a review, later dismissed

2022-06-15 15:07 UTC, kirchet approved these changes

2022-06-17 10:05 UTC, kirchet approved these changes

2022-06-20 15:00 UTC, merged