Fix #752 Series data still in memory after using setdata
tradingview/lightweight-charts pull request #755
Opened 2021-06-09 15:10 UTC by edew

**Type of PR:** Bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #752 
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**

Currently when a series is remove (i.e. it is updated with empty data `[]`) the library does not properly handle removing that data.

Internally this is because `DataLayer._syncIndexesAndApplyChanges` doesn't include the removed series in the returned `DataUpdateResponse`.

This PR fixes the logic so that removed series are included in the update response.

2021-06-09 16:26 UTC, timocov requested changes
The fix looks good for me, a few comments regarding tests/other changed files. btw, would you mind to add graphics tests as well?

2021-06-09 16:26 UTC, timocov commented on tests/unittests/data-layer.spec.ts
> +			const updateResult = dataLayer.setSeriesData(series1, []);
what if tests will be run in random order? Probably now the result depends on order of tests and probably this is not good. Can we either merge all `it`s into one or make tests independent of each other?

2021-06-09 16:26 UTC, timocov commented on src/api/data-layer.ts
> +				dataUpdateResponse.series.set(series, { data: [], fullUpdate: true });
would you mind to leave a comment here why do we need this here please?

2021-06-09 16:26 UTC, timocov commented on .gitignore
> +.DS_Store
hm, probably it should be system-wide ignore 😂 I'm just wondering why we have an ignore item for `*.pyc` files, but I think that ignoring OS-specific files shouldn't be a project-related thing (in this case we'd need to add some windows-specific files, linux-specific etc)

2021-06-11 11:12 UTC, timocov commented on tests/unittests/data-layer.spec.ts
> +		expect(updateResult1.timeScale.baseIndex).to.be.equal(0, 'expected base index to be 0');
shouldn't it be 9 here? we had 2 series with 10 data items each and just removed one of them so probably baseIndex value shouldn't be changed after removal?

2021-06-11 11:12 UTC, timocov commented on tests/unittests/data-layer.spec.ts
> +		expect(updateResult3.timeScale.baseIndex).to.be.equal(0, 'expected base index to be 0');
the same here about baseIndex value

2021-06-11 11:36 UTC, edew commented on tests/unittests/data-layer.spec.ts
> +		expect(updateResult1.timeScale.baseIndex).to.be.equal(0, 'expected base index to be 0');
👍 This is because the test data has invalid `time`s, so the index of all data points is `0`.

2021-06-11 12:54 UTC, timocov approved these changes

2021-06-11 12:54 UTC, merged