Add fixRightEdge time scale option
tradingview/lightweight-charts pull request #765
Opened 2021-06-16 13:38 UTC by edew

**Type of PR:** Enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #218 
- [x] Includes tests
- [x] Documentation update

**Overview of change:**

This adds a `fixRightEdge` option. Logically it's the same as `fixLeftEdge` but for the right.

These changes include logic to limit time scale bar spacing to `width / number of points` when **both** `fixRightEdge` and `fixLeftEdge` are enabled. This is so that zooming-out is prevented if it would cause either the first or last point to move too far from an edge.

2021-06-16 14:21 UTC, timocov requested changes
I think we need to have the following test cases here:
1. Applying `fixRightEdge` at the start and make sure that it doesn't allow you to scroll to the future
1. Open chart, scroll to the future, apply `fixRightEdge` in a timeout and make sure that it fixes the current position
1. Open chart, scroll to _the past_, apply `fixRightEdge` in a timeout and make sure that it does nothing
1. Open chart, apply `fixRightEdge` in a timeout and make sure that it doesn't allow you to scroll to the future
1. Open chart with enabled `fixRightEdge`, then disable it after some time and then you should be able to scroll to the future
1. Open chart with enabled both `fixLeftEdge` and `fixRightEdge` and it shouldn't allow you to scroll to the past/future
1. Open chart, enable both `fixLeftEdge` and `fixRightEdge` after some time and it shouldn't allow you to scroll to the past/future (also it should correct the position _and_ barSpacing value)
1. Open the chart, zoom in the data so you have a data from the left and from the right edges, enable `

Probably you cover some of cases in your test cases already.

2021-06-16 14:21 UTC, timocov commented on tests/e2e/graphics/test-cases/applying-options/fix-both-edges.js
> +		setTimeout(() => resolve(), 1000);
what this test case tests exactly?

btw if you down need to wait a time and use async operations in your test case - you can just skip returning a promise and the test runner will handle it correctly, e.g. https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/months-chart.js

2021-06-16 14:21 UTC, timocov commented on tests/e2e/graphics/test-cases/applying-options/fix-right-edge.js
> +		setTimeout(() => resolve(), 1000);
shouldn't we set both fixRightEdge and fixLeftEdge here? just because the name of test case is `applying-options/fix-right-edge` so a bit confusing

2021-06-17 14:28 UTC, timocov commented on src/model/time-scale.ts
> +			this.setRightOffset(0);
why not `_correctOffset` method? it looks like it does what we need to? and we wouldn't need to check current value then

2021-06-17 15:03 UTC, edew commented on src/model/time-scale.ts
> +			this.setRightOffset(0);
I thought that the `_correctOffset` logic would cause the right offset to the wrong value in some cases... but I've tested it just now and it seems to work fine so I will change this 👍 .

2021-06-17 15:16 UTC, timocov approved these changes

2021-06-17 15:17 UTC, merged