Last price animation
tradingview/lightweight-charts pull request #797
Opened 2021-07-27 12:51 UTC by kirchet

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #567
- [ ] Includes tests
- [x] Documentation update

**Overview of change:**

Added possibility to enable animation on changing area/line series' last price

2021-08-03 12:24 UTC, kirchet commented on src/views/pane/series-last-price-animation-pane-view.ts
> +					if (timeToAnimationEnd < LasPriceAnimationMode.OnDataUpdate / 4) {
```suggestion
					if (timeToAnimationEnd < Constants.AnimationPeriod / 4) {
```

2021-08-03 16:03 UTC, timocov requested changes

2021-08-03 16:03 UTC, timocov commented on src/views/pane/series-last-price-animation-pane-view.ts
> +		throw new Error('Last price animation internal logic error');
can't we use `ensureDefined`/`assert` functions here?

2021-08-03 16:19 UTC, kirchet commented on docs/constants.md
> +- `LasPriceAnimationMode.OnDataUpdate` - animation is active some time after data update.
No, it's not. For now it's 2600 msecs

2021-08-03 16:26 UTC, kirchet commented on src/views/pane/series-last-price-animation-pane-view.ts
> +		throw new Error('Last price animation internal logic error');
Yes, we can, but if we'll use `assert` we'll need to wrap `currentStageData` with `ensureDefined` as well. If we'll use only `ensureDefined` then it'll be not so informative without this message

2021-08-03 16:30 UTC, timocov commented on src/views/pane/series-last-price-animation-pane-view.ts
> +		throw new Error('Last price animation internal logic error');
> but if we'll use assert we'll need to wrap currentStageData with ensureDefined as well

We don't, TypeScript is smart enough to handle it itself: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoIIAmMsCAXIgEZxwA2GyYANIgLYbrIDmGA-BaihYYYLgEoKaTDlSICYYqSQBvAFABIGMES4AhPMXwwYxGvXqoACyxwA7ojAZ7AUSw2suAOQBBdNiWIwMgw9ISeiADUOuycPIi8iJ4U4VExqNwYiMmeYmIA3BoAvqrFqoQYELTIWJnygoE0FGAgrJTYiAA+iODlwCIYhAWqwDQAdFBwzgAeAA4IGGCwyLS4+aqqUv64I3CIugC8+90KGH2OhCyeaRk5Qzvjk7PzizDLqwVAA

2021-08-03 16:31 UTC, timocov commented on docs/area-series.md
> +        lastPriceAnimation: 1,
Also, could you enable this new option in coverage tests please?

2021-08-24 12:57 UTC, kirchet commented on src/model/idata-source.ts
> +	topPaneViews?(pane: Pane): readonly IPaneView[];
Added docs

2021-08-24 12:58 UTC, kirchet commented on src/model/series.ts
> +			setTimeout(() => this.model().cursorUpdate(), 0);
Fixed

2021-08-24 12:58 UTC, kirchet commented on docs/line-series.md
> +        lastPriceAnimation: 1,
Fixed

2021-08-24 12:58 UTC, kirchet commented on docs/area-series.md
> +        lastPriceAnimation: 1,
Done

2021-08-24 12:58 UTC, kirchet commented on src/views/pane/series-last-price-animation-pane-view.ts
> +		throw new Error('Last price animation internal logic error');
Fixed

2021-09-02 11:18 UTC, timocov commented on src/model/idata-source.ts
> +	topPaneViews?(pane: Pane): readonly IPaneView[];
Can you point out on them please?

2021-09-02 11:20 UTC, timocov approved these changes

2021-09-02 14:58 UTC, merged