Fix series draw in wrong order
tradingview/lightweight-charts pull request #800
Opened 2021-07-28 04:10 UTC by thanhlmm

**Type of PR:** Bugfix

**PR checklist:**

- [x] Addresses an existing issue: Fix wrong draw order #794
- [x] Includes tests
- [ ] Documentation update

**Overview of change:**
Change the way we sort sources

**Is there anything you'd like reviewers to focus on?**

2021-07-28 04:16 UTC, thanhlmm commented
@timocov https://github.com/tradingview/lightweight-charts/blob/master/src/model/pane.ts#L169
The logic is that new added source will get a lower zorder (-1, -2,...). It does not feel like normal standard, `zIndex` in css for examples

2021-07-29 10:03 UTC, timocov requested changes

2021-07-29 10:03 UTC, timocov commented on src/model/sort-sources.ts
> +		return (ensureNotNull(ensureNotNull(s2.zorder())) - ensureNotNull(s1.zorder()));
It seems that the order will be different now? I'd say that issue is in the code you mentioned in https://github.com/tradingview/lightweight-charts/pull/800#issuecomment-887996141, since it's strange that the new created series are back of previous ones. This change affects the order so basically our zorder will have different meaning and I don't think that this is what we want to have.

I'd say the new series should have `previous max + 1` zorder just to be at top of all previous ones so it might be expected to others who creates the series.

2021-07-29 10:32 UTC, thanhlmm commented on src/model/sort-sources.ts
> +		return (ensureNotNull(ensureNotNull(s2.zorder())) - ensureNotNull(s1.zorder()));
I will update it as `previous max + 1`. I'm not sure that the previous logic is there for any other reason so I make as little change as possible

2021-07-29 11:01 UTC, timocov approved these changes

2021-07-29 11:06 UTC, timocov commented on tests/e2e/graphics/test-cases/series/line-overlap.js
> +export function runTestCase(container) {
```suggestion
function runTestCase(container) {
```

2021-07-29 11:08 UTC, thanhlmm commented on tests/e2e/graphics/test-cases/series/line-overlap.js
> +export function runTestCase(container) {
In debug, I can import the test case to live test it by doing
```js
<script type="module">
  import { runTestCase } from './tests/e2e/graphics/test-cases/series/line-color-function.js';
  runTestCase(document.getElementById('container'));
</script>
```

2021-07-29 11:09 UTC, timocov commented on tests/e2e/graphics/test-cases/series/line-overlap.js
> +export function runTestCase(container) {
Oh, didn't know that 👍 Our test system isn't ready for that yet so just removed export keyword for now to make it work in CI

2021-07-29 12:29 UTC, merged

2021-07-29 12:29 UTC, timocov commented
@thanhlmm thanks for your work! Merged now.