Add chart export background
tradingview/lightweight-charts pull request #801
Opened 2021-07-28 04:23 UTC by thanhlmm

**Type of PR:** bugfix

**PR checklist:**

- [x] Addresses an existing issue: fixes #798 
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**
Add chart background when exporting

**Is there anything you'd like reviewers to focus on?**

2021-07-29 10:08 UTC, timocov commented
@thanhlmm can you add a test case for that please? Just to be sure that 1) the change fixes the issue 2) we won't break it in the future. I think you can slightly modify this test case https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/take-screenshot.js.

2021-07-29 12:30 UTC, timocov commented
@thanhlmm it seems that the test case works fine, probably something is missed?

2021-07-29 12:32 UTC, thanhlmm commented
I added new test case

2021-07-29 12:57 UTC, timocov commented
> it seems that the test case works fine, probably something is missed?

Let me explain a bit. e2e tests are screenshots-based tests which are comparing what the library from merge-base commit and from PR branch are generating. Thus, if you fixed something and added e2e test case for that we expect that the tests to be failed as soon as there should be a difference between master branch and your changes. If tests are passed that means that a test doesn't actually check the issue.

2021-07-29 13:26 UTC, thanhlmm commented
Updated. Thanks

2021-07-29 16:30 UTC, timocov commented on src/gui/chart-widget.ts
> +		ctx.globalCompositeOperation = 'source-over';
I don't think that this code is the issue actually. If you look closer to the screenshot you can see that there are still the issue with screenshots and looks like the issue is in different place.

How it is now (in master branch):

![image](https://user-images.githubusercontent.com/3112183/127529372-36725b59-3822-4a41-a800-e5a3c72bb052.png)

How it is in this PR:

![image](https://user-images.githubusercontent.com/3112183/127529465-44a2c224-3db6-401e-8d85-9686c6798492.png)

Differences:
![image](https://user-images.githubusercontent.com/3112183/127529450-22d80986-2587-49ca-b9fb-59c68f51c813.png)

- looks like a small dot of the right axis still is not presented on the screenshot
- there is some overlapping of time axis and something else so we don't have a border in some area

It seems that the issue is at 286 line, so instead of `targetX = firstPane.getSize().w;` we should do `targetX += firstPane.getSize().w;` to add left pane's width to current coordinate. If you remove this change and only replace `=` with `+=` it will works correctly 🙂 Single character fix 😄

2021-07-29 16:31 UTC, timocov requested changes
It seems that the fix is made in wrong place. Look at my comment above

2021-07-30 08:35 UTC, timocov approved these changes

2021-07-30 08:35 UTC, timocov commented
Thank you for your contribution!

2021-07-30 08:35 UTC, merged