WIP: fix multi-pane feature
tradingview/lightweight-charts pull request #824
Opened 2021-08-24 12:51 UTC by ntf

**Type of PR:** enhancement

**PR checklist:**

- [ ] Addresses an existing issue: fixes #50 
- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**
This is base on the pane widget and pane separator feature previously implemented in 22c6b03897c926cb9a0295d9b0bbc4fe2b5d83a5.

**Is there anything you'd like reviewers to focus on?**
API design. New API added so far (To be finalized) 
- subscribePaneResize 
- unsubscribePaneResize

Demo here: https://jsfiddle.net/adrianntf/6qea5ytv/2/

2021-09-11 18:01 UTC, ntf commented
Things I have implemented so far:

- series option to configure which pane a series should be rendered ( pane: number to SeriesOptionsCommon )
- `ChartApi#removePane(index: number)` so that you can remove a pane (and series on it) programmatically.
- `ChartApi#swapPane(first: number, second: number)` for swapping the positions of the two pane.
- code to handle series.applyOptions( { pane: newIndex } );
- `ChartApi#getPaneElements()` for getting container elements to each pane. (I need the container to draw legends to each pane)

Things I am also implementing but not going to be included in this PR:

- React binding with pane and legend supports

2023-02-10 06:36 UTC, FairyWorld commented
> resolved merge conflicts with tradingview's master branch

There is a conflict with the latest version. I hope you can solve it

2023-09-18 12:14 UTC, 0220tiezo1323 requested changes
No

2024-01-05 23:59 UTC, carere commented
Does this feature still in the loop for future release ?
@qwpto Where is the fork with this feature implemented ?

2024-01-06 05:16 UTC, qwpto commented
> Does this feature still in the loop for future release ? @qwpto Where is the fork with this feature implemented ?

@carere There's a pull request link in my comment above where it can be found.

2024-02-07 23:40 UTC, rwitzlib commented
Here is an updated fork people can reference if they'd like: https://github.com/rwitzlib/lightweight-charts
Currently updated to v4.1.3 but Ill try to keep this updated until multi-pane is officially supported

2024-02-11 22:03 UTC, carere commented
@rwitzlib Can you explain to me how can I add another pane to the chart with your fork ?

2024-02-13 04:47 UTC, rwitzlib commented
> @rwitzlib Can you explain to me how can I add another pane to the chart with your fork ?

Of course, I left a comment here: https://github.com/tradingview/lightweight-charts/issues/50#issuecomment-1940418228 so its a bit easier for people to see

2024-07-25 17:18 UTC, SlicedSilver commented
The changes within this PR were included in the #1557 PR and this feature will be part of our next major release so I'm going to close this PR.

2024-07-25 17:18 UTC, closed without merging