Kinetic scroll animation
tradingview/lightweight-charts pull request #825
Opened 2021-08-24 17:38 UTC by kirchet

**Type of PR:** enhancement

**PR checklist:**

- [ ] Addresses an existing issue: fixes #
- [x] Includes tests
- [x] Documentation update

**Overview of change:**

![kinetic_animation](https://user-images.githubusercontent.com/1572087/130663518-09d50f53-4776-4096-a1c1-ea5b0e6231ae.gif)

2021-09-02 09:35 UTC, timocov requested changes

2021-09-02 09:35 UTC, timocov commented on src/gui/pane-widget.ts
> +			const now = Date.now();
would you mind to use `performance.now()` instead? just to avoid issues with changing date during the work

2021-09-02 09:35 UTC, timocov commented on src/gui/pane-widget.ts
> +type StartScrollPosition = Point & {
just curious why not `interface StartScrollPosition extends Point`? 🙂 it seems that we mostly use this approach over extending types with `&`

2021-09-02 14:06 UTC, kirchet commented on src/gui/pane-widget.ts
> +			const now = Date.now();
Fixed

2021-09-02 14:06 UTC, kirchet commented on src/gui/pane-widget.ts
> +type StartScrollPosition = Point & {
Fixed

2021-09-02 14:32 UTC, timocov approved these changes

2021-09-02 14:33 UTC, merged

2022-01-03 20:40 UTC, mhtzghoul commented
Dose trading view use any library for chart animation like (mobile horizontal scroll smoothly ) and another events on chart or all of this is hard coded ?

2022-01-04 09:39 UTC, timocov commented
@mhtzghoul as you can see everything is implemented internally and we don't rely on any external implementation for animations.

2022-01-18 11:01 UTC, mhtzghoul commented
@timocov  i have question 
this function ( getPosition(time: number) ) return the Last position of animation One time , Or by accumulation and repetition the position ?

2022-01-18 11:03 UTC, mhtzghoul commented
@timocov  i have question
this function ( getPosition(time: number) ) return the Last position of animation One time , Or by accumulation and repetition the position ?

2022-01-18 11:04 UTC, timocov commented
@kirchet ^^ please

2022-01-18 11:16 UTC, kirchet commented
Not sure that I understood the question.
`getPosition(time: number)` returns animation position accordingly to provided `time`. Internally it stores start animation time and duration. If `time - startTime >= duration` then it returns final position