Gradient background
tradingview/lightweight-charts pull request #828
Opened 2021-08-25 15:03 UTC by kirchet

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #831
- [x] Includes tests
- [x] Documentation update

**Overview of change:**

![image](https://user-images.githubusercontent.com/1572087/130815320-47925d19-36bd-428d-81b5-be81f973fa2a.png)

2021-09-01 17:41 UTC, timocov requested changes

2021-09-01 17:41 UTC, timocov commented on docs/constants.md
> +## ColorType
I agree with @eugene-korobko about `BackgroundType`. If we'll decide to use this (or similar) type somewhere else we can decide whether we need to create a new type for that or re-use with renaming the old one.

2021-09-01 17:41 UTC, timocov commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
What do you think about having something like `background: { type: Solid; color: string } | { type: Gradient; topColor: string; bottomColor: string }`? It won't be hard to implement it but will be better for readability and support to avoid any misunderstanding in the options IMO.

2021-09-01 17:41 UTC, timocov commented on docs/constants.md
> +## ColorType
If we'll use the approach with typed `background` property (with 2 different sets of possible values) then `ColorType` looks better though.

2021-09-01 17:41 UTC, timocov commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
But we need to not forget about breaking change and add migration code

2021-09-01 17:41 UTC, timocov commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
It might even have `steps: ({ color: string; level: number; })[];` or so instead of top/bottom colors to support multi-level gradients.

2021-09-01 17:41 UTC, timocov commented on src/model/layout-options.ts
> +export enum ColorType {
```suggestion
export const enum ColorType {
```

2021-09-01 17:41 UTC, timocov commented on src/model/series.ts
> +	private _markerBorderColor(): string | null {
is this change related to the MR?

2021-09-01 17:41 UTC, timocov commented on src/model/chart-model.ts
> +	public backgroundTopColor(): string {
is this and `backgroundBottomColor` are used anywhere (so they are public)?

2021-09-01 17:41 UTC, timocov commented on src/helpers/color.ts
> +export function gradientColorAtPercent(topColor: string, bottomColor: string, percent: number): string {
unit tests for the new public functions pls

2021-09-02 11:25 UTC, timocov commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
The type might be even kind of `VerticalLinearGradient` to specify the direction of the gradient

2021-09-02 11:55 UTC, kirchet commented on src/model/series.ts
> +	private _markerBorderColor(): string | null {
Yes

2021-09-02 13:43 UTC, kirchet commented on src/model/chart-model.ts
> +	public backgroundTopColor(): string {
Yes

2021-09-02 13:44 UTC, kirchet commented on src/helpers/color.ts
> +export function gradientColorAtPercent(topColor: string, bottomColor: string, percent: number): string {
Added

2021-09-02 13:44 UTC, kirchet commented on src/model/layout-options.ts
> +export enum ColorType {
Fixed

2021-09-02 13:46 UTC, kirchet commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
Replaced with one option `background` with type `export type Background = SolidColor | VerticalGradientColor;`.

2021-09-02 15:28 UTC, timocov requested changes

2021-09-02 15:28 UTC, timocov commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
```suggestion
|`background`|[Background](./#background)| `{ type: ColorType.Solid, color: '#ffffff' }` |Chart and scales background|
```

2021-09-02 15:28 UTC, timocov commented on src/model/layout-options.ts
> +	 * @internal
I think in this case this property will be omitted so this deprecation will have no sense for users. I'd say we need to keep it for now (at least if we wan't to merge it to the next minor version)

2021-09-02 15:41 UTC, kirchet commented on src/model/layout-options.ts
> +	 * @internal
Fixed

2021-09-02 15:41 UTC, kirchet commented on docs/customization.md
> +|`backgroundGradientEndColor`|`string`|`#ffffff`|Chart and scales background bottom color if background type is gradient|
Fixed

2021-09-02 16:02 UTC, timocov approved these changes

2021-09-02 16:02 UTC, merged