Add methods for getting bar info by logical index
tradingview/lightweight-charts pull request #849
Opened 2021-09-20 08:46 UTC by tv-ksi

**Type of PR:** enhancement

**PR checklist:**

- [ ] Includes tests
- [ ] Documentation update

**Overview of change:**

Add method `getBarInfoByLogicalIndex` to series API  for getting bar price with change value
Add optional `logiacalIndex` param to mouse event handlers

2021-09-20 11:18 UTC, kirchet requested changes

2021-09-20 11:18 UTC, kirchet commented on src/api/series-api.ts
> +		const bar = series.dataAt(logicalIndex as unknown as TimePointIndex) as SeriesDataAtTypeMap[TSeriesType];
We should pass `PlotRowSearchMode` as an argument and use it directly:

```
public getBarInfoByLogicalIndex(logicalIndex: Logical, searchMode: PlotRowSearchMode = PlotRowSearchMode.Exact): BarPriceInfoAtTypeMap[TSeriesType] | null {
    return series.bars().search(logicalIndex as TimePointIndex, searchMode);
}
```

2021-09-20 11:18 UTC, kirchet commented on src/index.ts
> +export { Logical } from './model/time-data';
Here we re-export only const enums

2021-09-20 11:18 UTC, kirchet commented on src/model/bar.ts
> +	change: number | undefined;
We don't need `value` and `change`. We need only `BarPrice` | `BarPrices`

2021-09-20 11:33 UTC, timocov requested changes

2021-09-20 11:33 UTC, timocov commented on docs/events.md
> +- `logicalIndex`: (`Logical`, optional) - logical index
why is it optional? it seems that a logical index always exists?

2021-09-20 11:33 UTC, timocov commented on src/api/iseries-api.ts
> +	getBarInfoByLogicalIndex(logicalIndex: Logical): BarPriceInfoAtTypeMap[TSeriesType] | null;
we need to add this function to the docs

2021-09-20 11:33 UTC, timocov commented on src/api/iseries-api.ts
> +	getBarInfoByLogicalIndex(logicalIndex: Logical): BarPriceInfoAtTypeMap[TSeriesType] | null;
btw, it seems that we don't use `get` prefixes for getters (see `barsInLogicalRange` or `options`)

2021-09-20 11:33 UTC, timocov commented on src/api/ichart-api.ts
> +	logicalIndex?: Logical;
why not just `index`? I don't think that we have different indexes...

2021-09-20 11:33 UTC, timocov commented on src/api/series-api.ts
> +				change: prevBar ? bar.close - prevBar.value[PlotRowValueIndex.Close] : undefined,
I don't think that this is a good idea to return any kind of "change". Why did you choose close field over any other fields? Could you calculate a "change" value based on 2 values outside of lightweight-charts code?

2021-09-20 11:33 UTC, timocov commented on src/api/series-api.ts
> +			(logicalIndex - 1) as unknown as TimePointIndex,
why do you use `as unknown` here? I think it should work without it (just `as TimePointIndex`)

2021-09-20 11:33 UTC, timocov commented on src/gui/chart-widget.ts
> +			? this._model.timeScale().coordinateToIndex(point?.x) as unknown as Logical
you don't need to convert `number` to `Logical` via `unknown`

2021-09-20 12:11 UTC, kirchet commented on docs/events.md
> +- `logicalIndex`: (`Logical`, optional) - logical index
I think for the same reason as `time`

2021-09-20 13:18 UTC, timocov commented on docs/events.md
> +- `logicalIndex`: (`Logical`, optional) - logical index
We might not have a `time` because a crosshair might be outside of the data and we won't extrapolate the time in this case, but for index the situation is different, so I'm just curious in what cases `index` might be omitted.

2021-09-21 12:21 UTC, tv-ksi commented on src/gui/chart-widget.ts
> +			? this._model.timeScale().coordinateToIndex(point?.x) as unknown as Logical
```
TS2352: Conversion of type 'TimePointIndex' to type 'Logical' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.   Type 'TimePointIndex' is not comparable to type '{ [Symbol.species]: "Logical"; }'.     Types of property '[Symbol.species]' are incompatible.       Type '"TimePointIndex"' is not comparable to type '"Logical"'.
```

2021-09-21 12:37 UTC, kirchet commented on docs/events.md
> +- `logicalIndex`: (`Logical`, optional) - logical index
But what logical index should we provide if a crosshair is out of a chart?

2021-09-21 12:41 UTC, kirchet commented on src/model/series.ts
> +}
1. Let's move this code before `Series` class
2. There is no need to have a result variable, we can just return a resul in both cases

2021-09-21 12:43 UTC, kirchet commented on docs/series-basics.md
> +Returns a bar price for the series by the provided logical index. If no one bar satisfy the index, `null` is returned.
Maybe bar prices? Also if the structure of bar prices is already described we need to add a link to this description here

2021-09-21 12:49 UTC, kirchet commented on docs/series-basics.md
> +- `searchMode`(`PlotRowSearchMode`) - a search mode
Seems like it's the same structure as in `subscribeCrosshairMove` callback argument `seriesPrices`. It's already described here: https://github.com/tradingview/lightweight-charts/blob/master/docs/events.md#types. You can just add a link to this description here and modify the existing description if you want

2021-09-21 12:49 UTC, kirchet commented on docs/series-basics.md
> +- `close`(`BarPrice`) - an item close
Seems like it's the same structure as in `subscribeCrosshairMove` callback argument `seriesPrices`. It's already described here: https://github.com/tradingview/lightweight-charts/blob/master/docs/events.md#types. You can just add a link to this description here and modify the existing description if you want

2021-09-21 14:55 UTC, tv-ksi commented on docs/series-basics.md
> +- `close`(`BarPrice`) - an item close
It's not, here it's an object or a number, the seriesPrices it is a number or a OHLC (tuple)

2021-09-21 17:39 UTC, kirchet commented on docs/series-basics.md
> +const barPrices: object | null = barSeriesApi.barByIndex(logicalIndex, PlotRowSearch.NearestRight);
Why do you use TS? All other examples are on JS

2021-09-21 17:45 UTC, kirchet commented on docs/series-basics.md
> +- `close`(`BarPrice`) - an item close
> The object keys are series APIs, values are prices

Seems like these prices are the same as here. I suggest to move there the description of this type and add a link to it.

2021-09-21 17:50 UTC, kirchet commented on docs/constants.md
> +- `PlotRowSearchMode.NearestRight` - search the nearest plot from right side
Actually we search at exact index or nearest non-empty left/nearest non-empty righ bar prices (if at exact indes nothing found) correspondingly for `PlotRowSearchMode.NearestLeft` / `PlotRowSearchMode.NearestRight`

2021-09-22 07:25 UTC, tv-ksi commented on docs/series-basics.md
> +- `close`(`BarPrice`) - an item close
OHLC it's a tuple [open: BarPrice, high: BarPrice, low: BarPrice, close: BarPrice], it's not the same as object

2021-09-22 14:26 UTC, kirchet commented on docs/series-basics.md
> +const barPrice = lineSeriesApi.barByIndex(logicalIndex, PlotRowSearch.NearestLeft);
```suggestion
const barPrice = lineSeriesApi.barByIndex(logicalIndex, LightweightCharts.PlotRowSearch.NearestLeft);
```

2021-11-18 10:11 UTC, closed without merging