Added support for custom colors for candlestick, bar and line series
tradingview/lightweight-charts pull request #881
Opened 2021-11-05 12:27 UTC by timocov

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #195
- [x] Includes tests
- [x] Documentation update

**Overview of change:**

There is a breaking change in types so it should be released in a major version.

It is not finished yet since we need to decide how to solve the issue with painting a line, see https://github.com/tradingview/lightweight-charts/issues/195#issuecomment-961850692.

**Is there anything you'd like reviewers to focus on?**

2022-01-10 17:59 UTC, timocov commented
It seems that it is not breaking changes so we could merge it to v3.8. I'll check this and post an update later.

2022-01-11 11:14 UTC, kirchet requested changes

2022-01-11 11:14 UTC, kirchet commented on src/model/series-bar-colorer.ts
> +			result.barBorderColor = currentBar.color;
If we have `barColor` and `barBorderColor` shouldn't we add possibility to rewrite both these colors independently (i.e. add `borderColor` to `BarData` and `BarPlotRow`)?

2022-01-11 11:22 UTC, timocov commented on src/model/series-bar-colorer.ts
> +			result.barBorderColor = currentBar.color;
It seems that for bars we cannot specify a border color via options https://tradingview.github.io/lightweight-charts/docs/api/interfaces/BarStyleOptions, so that's why we don't have it here

2022-01-11 18:20 UTC, timocov commented
So based on the diff we got in the API we have the following:
- there are 3 new interfaces: `CandlestickData`, `OhlcData` and `SingleValueData`
- `BarData` interface has a new optional property `color`
- `LineData` interface has a new optional property `color`
- the type for Candlestick, Area and Baseline series has been changed from `BarData`, `LineData` and `LineData` to `CandlestickData`, `SingleValueData` and `SingleValueData` correspondingly

A new optional property isn't an issue so we can ignore it. The same for new interfaces - it was impossible to use them with the previous versions so it shouldn't be a problem.

So the only possible issue we might have if you're using `LineData` interface for area/baseline series and/or `BarData` interface for candlestick series so we need to be sure that [the following code will compile without errors](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVQCoGFWgKYGcYCG4ANHADLAB22AIgYaQEIFR0NwDqAFsDHmAQDGtegVKCo2etnRcW8AL5wAZlAgg4AcgA2wAOZcYAd2z7DAWkFzYuTQG4AUA8ERK+OFflwAvB8nTZeQAKTUoIOBB6Pig4Izl4LmxJTQBKR2dXdxYpAGUk4DwfD2sYADoCABMKgEF-PKgC3CC0jLd4ACMCXGxdanrGos9Ycqrmbt7sfrxmxxc2uE6oKdxBkpGK9AJKCu08GGBBAGtlmac5rP82AgAucioRQgBtAF0ix4c4T8Q4fZBsW4AjHAuigMFg-vgiGBSAA3AjaACu-zgQIUxAcz3S2QIy1K3RgVyC2KuLVa7k643uV1uFGoVxebw+XyQv2RQJBaEwOEhJDgcMRbLgaIx6QpPXuuPxhLFExJ6XOHRY1LgzFYogZvneX2+rMBwJWnPBeyhpAgYGwlEBpB4BitcG0ECMdsEDu6euFmKci0l2AJoiCizlQA) with the new version as well:

```ts
import { UTCTimestamp, LineData, BarData, WhitespaceData, createChart } from 'lightweight-charts';

const chart = createChart('no matter what here');

const areaSeries = chart.addAreaSeries();
const baselineSeries = chart.addBaselineSeries();
const barSeries = chart.addCandlestickSeries();

const areaData: LineData[] = [
    { time: 1 as UTCTimestamp, value: 1 },
];

areaSeries.setData(areaData);

const baselineData: LineData[] = [
    { time: 1 as UTCTimestamp, value: 1 },
];

baselineSeries.setData(baselineData);

const barData: BarData[] = [
    { time: 1 as UTCTimestamp, open: 1, high: 1, low: 1, close: 1 },
];

barSeries.setData(barData);
```

I just tried to use this code the version from this branch and it seems working fine so we can say that this branch has no breaking changes and we can merge it to master branch and release as part of upcoming v3.8 release.

2022-01-11 18:21 UTC, merged