Add docs versioning
tradingview/lightweight-charts pull request #922
Opened 2021-11-30 18:02 UTC by edew

**Type of PR:** enhancement

**PR checklist:**

- [ ] Addresses an existing issue: fixes #
- [ ] Includes tests
- [x] Documentation update

**Overview of change:**

This PR adds enables Docusaurus' versioning feature. We will structure our docs according to the first "use case" mentioned [here in the Docusaurus docs](https://docusaurus.io/docs/versioning#figure-out-the-behavior-for-the-current-version): 

> You release v1, and start immediately working on v2 (including its docs)

So we have a "next" version that shows the work in progress documentation, and specific versions like 3.7.0 that contain the documentation for the library 

A version has been added for 3.7.0. 

I've added an index page with a hero section and a randomly generated example chart. We should improve this index page in the future (we could put an interactive playground here for example) but for now we need something to show when the root of the site is requested.

**Is there anything you'd like reviewers to focus on?**

Linking between versioned docs [requires the .md extension to be included](https://docusaurus.io/docs/versioning#linking-docs), hence the changes in this PR.

2021-12-01 11:22 UTC, timocov requested changes

2021-12-01 11:22 UTC, timocov commented on scripts/cache-typings-from-unpkg.js
> +			reject(error);
shouldn't it close `file` stream here in this case?

2021-12-01 11:22 UTC, timocov commented on website/docusaurus.config.js
> +const path = require('path');
would you mind to put it as the first statement instead? just to make sure that built-in modules are first, then deps and then out modules

2021-12-01 11:22 UTC, timocov commented on website/docusaurus.config.js
> +	name: 'lightweight-charts',
do you know where this field is used in generated files?

2021-12-01 11:22 UTC, timocov commented on website/docusaurus.config.js
> +								to: `/docs/${latestVersion}`,
do we need to specify a version here? it looks like it will always redirect to the latest version instead of navigating inside selected one?

2021-12-01 11:22 UTC, timocov commented on website/package.json
> +    "lightweight-charts": "~3.7.0",
what version it should be here? always latest one?

2021-12-01 11:22 UTC, timocov commented on website/package.json
> +    "use-resize-observer": "^8.0.0"
```suggestion
    "use-resize-observer": "~8.0.0"
```

pls

2021-12-01 11:22 UTC, timocov commented on website/src/pages/index.tsx
> +// wow, meta!
meta? 🤔

2021-12-01 11:22 UTC, timocov commented on website/src/pages/index.tsx
> +import useResizeObserver from 'use-resize-observer'
would you mind to add `.tsx` files to be handled by eslint as well?

2021-12-01 11:22 UTC, timocov commented on website/src/pages/index.tsx
> +function Hero(props: HeroProps) {
what does "Hero" mean? 🤔

2021-12-01 11:29 UTC, edew commented on website/README.md
> +npm run docusaurus docs:version 3.7.0
I think every release would be too much. Last `n` major/minor is good.

2021-12-01 11:33 UTC, edew commented on .circleci/config.yml
> +            node ./scripts/cache-typings-from-unpkg.js
Yes I guess adding this logic to the Docusaurus config would mean we can't forget to run it locally. 👍

2021-12-01 11:38 UTC, edew commented on website/src/pages/index.tsx
> +function Hero(props: HeroProps) {
> "The Hero image is often the prototypical visual element a visitor encounters on the site; ..."

Seems to be a commonly used name for "The huge thing at the top of the landing page".

Specifically in our case it's the component from Infima: https://infima.dev/docs/components/hero

2021-12-01 11:39 UTC, edew commented on website/docusaurus.config.js
> +	name: 'lightweight-charts',
It's the `title` field in the front matter for the `api/index.md` file.

2021-12-01 11:40 UTC, edew commented on website/sidebars.js
> +		'intro',
No unfortunately not.

2021-12-01 11:42 UTC, edew commented on website/docs/intro.md
> +[`createChart`](/api/index.md#createchart) is the entry-point for creating charts. You can use it to create as many charts as you need:
Yep! If it can't resolve a link it will write an error when building.

2021-12-01 12:28 UTC, edew commented on website/docusaurus.config.js
> +								to: `/docs/${latestVersion}`,
Yes that's true (it will link to the latest) but the footer links aren't version aware so `/docs` would be not found.

2021-12-06 10:24 UTC, timocov approved these changes

2021-12-06 10:29 UTC, merged