Api methods for getting data by index
tradingview/lightweight-charts pull request #934
Opened 2021-12-10 11:44 UTC by kirchet

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #414, #470 
- [x] Includes tests
- [x] Documentation update

**Overview of change:**

Added methods

- `ISeriesApi.getMarkers`
- `ISeriesApi.dataByIndex`

Changed time types everywhere in the public API to `Time`

2021-12-13 14:40 UTC, timocov requested changes

2021-12-13 17:36 UTC, kirchet commented on src/api/iseries-api.ts
> +	dataByIndex(index: Logical, mismatchDirection?: MismatchDirection): SeriesDataItemTypeMap[TSeriesType] | null;
https://github.com/tradingview/lightweight-charts/pull/934/commits/3353c9fc2d22731913a10b0a39eab3c97216dfa2

2021-12-13 17:39 UTC, kirchet commented on src/model/plot-data.ts
> +export type WhitespacePlotRow = Omit<PlotRow, 'value'>;
https://github.com/tradingview/lightweight-charts/pull/934/commits/f66ff411f50ad31585a491930410ca2f63f32436#diff-219c330dbd21b6f81cb7dc9b0945406461a0100fb85baa27ec048d621031e3d9R26-R27

2021-12-13 17:39 UTC, kirchet commented on src/api/series-api.ts
> +			// we should use here local variable, otherwise ts-transformer-properties-rename renames the field time to _internal_time
https://github.com/tradingview/lightweight-charts/pull/934/commits/f66ff411f50ad31585a491930410ca2f63f32436#diff-b5e5ef864e4f34adce2f659e3061587abfa34593384a15e68f48e196bf60e530R152-R156

2021-12-13 17:40 UTC, kirchet commented on src/model/series-data.ts
> +export type SeriesPlotRowWithWhitespaces<T extends SeriesType = SeriesType> = SeriesPlotRowTypeAtTypeMap[T] | WhitespacePlotRow;
https://github.com/tradingview/lightweight-charts/pull/934/commits/f66ff411f50ad31585a491930410ca2f63f32436#diff-d8fd74e8ac6eb3df9f41ed4c2aca57a3065b4f4beb1eb21961e94c48021b4b0dL19

2021-12-13 17:40 UTC, kirchet commented on src/model/time-scale.ts
> +	TickMarkWeight, Time,
https://github.com/tradingview/lightweight-charts/pull/934/commits/f66ff411f50ad31585a491930410ca2f63f32436#diff-fefb9f6a6e16812458e111078af1268f46c22a5bdc162e5e3a1e79562ace6a5fR22-R23

2021-12-13 22:59 UTC, timocov commented on src/api/series-api.ts
> +			// this doesn't work because of ts-transformer-properties-rename
it still doesn't work? 🤔

2021-12-14 15:01 UTC, kirchet commented on src/api/series-api.ts
> +			// this doesn't work because of ts-transformer-properties-rename
Seems that it's working now
Fixed: https://github.com/tradingview/lightweight-charts/pull/934/commits/f6e24e6637298194f22c63a768232d3243b6aeac

2021-12-15 14:33 UTC, timocov commented
Related to https://github.com/tradingview/lightweight-charts/issues/938

2021-12-15 14:33 UTC, timocov approved these changes

2021-12-15 14:33 UTC, merged