Docusaurus react tutorial
tradingview/lightweight-charts pull request #958
Opened 2021-12-31 10:11 UTC by romfrancois

**Type of PR:** enhancement

**PR checklist:**
- [x] Documentation update

**Overview of change:**
Adds a React tutorial to integrate LWC to a project from scratch.

2022-01-05 15:29 UTC, edew requested changes

2022-01-05 15:29 UTC, edew commented on website/docs/tutorials/react/tutorials.mdx
> +### series-type
Can we move these examples for each series to the corresponding section of series-types.md and replace the images there with interactive examples?

2022-01-05 15:29 UTC, edew commented on website/src/pages/_react/react-components.tsx
> +			// Careful as for some type data would have to be OHLC formatted as in
I think we should show the correct usage in our examples, so can we change this so `myData` is correct for OHLC data series?

2022-01-06 11:05 UTC, edew requested changes

2022-01-06 11:05 UTC, edew commented on .circleci/config.yml
> +      - run: cd website && npm install && cd -
Adding this step here won't do anything unfortunately. It's installing the `website` dependencies for the `install-deps` job and then throwing it away once the job ends.

This `install-deps` job would need to save the `website/node_modules` to the cache (see https://circleci.com/docs/2.0/caching/) so that it can use reused in later jobs (for example the lint job).

I'd move this step to the `lint-ts` job for now to quickly see if it fixes your issue. If it does then we can do it properly and take advantage for the CircleCI cache.

2022-01-06 11:08 UTC, romfrancois commented on .circleci/config.yml
> +      - run: cd website && npm install && cd -
And I thought it would be clever :( 
Thanks, will try that.

2022-01-07 13:16 UTC, edew requested changes

2022-01-07 13:16 UTC, edew commented on website/sidebars.js
> +				},
I don't think we need this?

Also if we only have one react tutorial file we can remove the react directory and just have a `tutorials/react.mdx` file (for example).

2022-01-07 13:16 UTC, edew commented on website/docs/series-types.mdx
> +import { ChartComponent } from "../src/pages/_react/react-components.tsx"
Like me mentioned this morning we can keep the images here for now and replace them with interactive charts in another PR. 💪

2022-01-07 13:16 UTC, edew commented on .circleci/config.yml
> +      - run: cd website && npm install && cd -
Now we know that this solves the error on CI we can create aliases for saving and restoring the `website/node_modules` directory to and from the cache.

Check out `restore-node-modules-cache` and `save-node-modules-cache` in this file for examples of how we do it for the root `node_modules`

2022-01-07 13:16 UTC, edew commented on .eslintrc.js
> +		{ selector: 'variable', format: ['camelCase', 'UPPER_CASE', ...additionalDefaultFormats] },
Why did we need to add this? 🤔

2022-01-07 15:54 UTC, romfrancois commented on website/sidebars.js
> +				},
Agreed with the second part.

As for the first one, if omitted sidebar will disappear when going into Tutorials/react.md

2022-01-07 15:58 UTC, romfrancois commented on .eslintrc.js
> +		{ selector: 'variable', format: ['camelCase', 'UPPER_CASE', ...additionalDefaultFormats] },
Otherwise I get errors lie

> react-components.tsx:24:14: Variable name `ChartComponent` must match one of the following formats: camelCase, UPPER_CASE [Error/@typescript-eslint/naming-convention]

Happy to check that one with you if the issue comes from my environment

2022-01-10 17:58 UTC, edew requested changes

2022-01-10 17:58 UTC, edew commented on website/docs/tutorials/react.mdx
> +};
I think we can simplify this further by

1. showing the example in Javascript (so removing the TypeScript syntax).
2. Combining this code block and the one below.

2022-01-10 17:58 UTC, edew commented on website/docs/tutorials/react.mdx
> +			mainChart = createChart(chartContainerRef.current, {
`mainChart` will be redeclared each time `ChartComponent` is called (i.e. on each render).

From eslint:
```
Assignments to the 'mainChart' variable from inside React Hook useEffect will be lost after each render.

To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. 

Otherwise, you can move this variable directly inside useEffect. (react-hooks/exhaustive-deps)eslint
```

2022-01-10 17:58 UTC, edew commented on website/docs/tutorials/react.mdx
> +export interface ChartProperties {
Can we include an example that shows how users can `update` series data as well as setting it? I imagine that would be one of the first questions we are asked.

2022-01-10 17:58 UTC, edew commented on website/docs/tutorials/react.mdx
> +id: howTo
```suggestion
id: react
```

Currently the path for this page is `/lightweight-charts/docs/tutorials/howTo`

2022-01-11 16:02 UTC, romfrancois commented on website/docs/tutorials/react.mdx
> +export interface ChartProperties {
As discuss let's revisit it later.

2022-01-12 17:13 UTC, timocov commented
It seems that this tutorial is addressing to #200

2022-01-12 17:41 UTC, justin-pierce commented
Would love if the tutorial touched on this: 

https://github.com/tradingview/lightweight-charts/issues/200#issuecomment-951563309

2022-01-13 16:05 UTC, romfrancois commented on website/docs/tutorials/react.mdx
> +			return () => window.removeEventListener('resize', handleResize);
Yes, that's what I was mentioning this morning.

2022-01-13 16:55 UTC, romfrancois commented on website/src/pages/_react/react-components.tsx
> +import { createChart, IChartApi, ISeriesApi, SeriesType } from 'lightweight-charts';
I'll remove this file as it's not used anymore

2022-01-13 16:57 UTC, romfrancois commented on website/docs/tutorials/react.mdx
> +import { SetupComponent } from "../../src/pages/_react/setup-component.tsx"
Rather than using internal code, I'd vote in favour of using a jsfiddle/codepen embedded example here. It would avoid having to maintain the code within this file vs possibility to do it directly on the example without impacting the doc.
+ it would go along the next phase which would be to replace all static images by a real example.

2022-01-18 11:00 UTC, timocov requested changes

2022-01-18 11:00 UTC, timocov commented on website/docs/tutorials/react.mdx
> +				series.setData(data);
it seems that this component is designed to be area component rather than a chart one since you're unable to change the type of series in runtime.

I as a consumer of this component might want to do the following from _the outside_ of this component so I might want to have an ability to have this in API:
- change the type of the series in runtime
- add new more series to the chart (or remove them)
- change visible range
- apply options to the chart

How it could be done? I think that this is the first question we will be asked about (and we were in #200 I believe). This example is quite simple and there is a place for this, but it won't work in real-world applications where you might want to have something more.

Probably we can leave this simple example as is, but we need to provide more complex example as well IMO.

2022-01-20 15:17 UTC, edew commented on .circleci/config.yml
> +            - install-deps-website
It works currently but we could clean it up

1. add the `install-deps` and `install-reps-website` [jobs](https://github.com/romfrancois/lightweight-charts/blob/docusaurus-react-tutorial/.circleci/config.yml#L94) to to the [`website` workflow](https://github.com/romfrancois/lightweight-charts/blob/docusaurus-react-tutorial/.circleci/config.yml#L368) like they are in the [`build-lint-test` workflow](https://github.com/romfrancois/lightweight-charts/blob/docusaurus-react-tutorial/.circleci/config.yml#L300).

2. combine the `checkout-with-deps-website` and `checkout-with-deps` [commands](https://github.com/romfrancois/lightweight-charts/blob/docusaurus-react-tutorial/.circleci/config.yml#L55). (Remove the website one and  add the `restore_cache: *restore-node-modules-cache-website` step to the original.

2022-01-20 15:38 UTC, timocov commented on .circleci/config.yml
> +            - install-deps-website
yeah, I thought about that it seems that we do the same things a bit differently in several places so we could refactor this part a bit

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +By following the steps below we assume you're familiar with Lightweight Chart, how to set up a project using it and how to render a chart.
```suggestion
By following the steps below we assume you're familiar with Lightweight Charts, how to set up a project using it and how to render a chart.
```

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +If you're familiar with Lightweight Chart you probably already know that a _Chart_ is a container that can contain one or more [_Series_](../series-types.md).
```suggestion
If you're familiar with Lightweight Charts you probably already know that a _Chart_ is a container that can contain one or more [_Series_](../series-types.md).
```

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +Each _Series_ has its own options (for instance [AreaStyleOptions](/api/interfaces/AreaStyleOptions.md), [LineStyleOptions](/api/interfaces/LineStyleOptions.md), etc) in addition to [Price](../price-
```suggestion
Each _Series_ has its own options (for instance [AreaStyleOptions](/api/interfaces/AreaStyleOptions.md), [LineStyleOptions](/api/interfaces/LineStyleOptions.md), etc) in addition to [price](../price-scale.md) and/or [time](../time-scale.md) scale.
```

the time scale is common for all series though. Probably we could rephrase it? What did you want to say here?

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +}
shouldn't we return a ChildComponent here for better understanding why it is so?

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +In essence, taking the example above, it means that a ChildComponent (aka Series) would be created first whilst requiring a ParentComponent (aka Chart).
```suggestion
In essence, taking the example above, it means that a `ChildComponent` (aka Series) would be created first whilst requiring a `ParentComponent` (aka Chart).
```

?

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +ChartContainer will be responsible for creating a **ref**[erence] that will hold functions to handle the lifecycle of the chart.
> **ref**[erence]

is this a special syntax for something? 🤔

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react-complex-example.mdx
> +import Code from '!!raw-loader!./../../src/pages/_react/complex-example.jsx';
btw do need to specify an extension for imports in mdx files? it seems that we don't this in ts/tsx files not js?

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react.mdx
> +The following only describes a relatively simple example that only renders an [areaSeries](../series-types.md#area) that could be tweaked to render any other type of [series](../series-types.md).
```suggestion
The following only describes a relatively simple example that only renders an [area series](../series-types.md#area) that could be tweaked to render any other type of [series](../series-types.md).
```

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react.mdx
> +For a more complete scenario where you could wrap Lightweight Chart into a component having sub components, please consult this [example](./react-complex-example).
```suggestion
For a more complete scenario where you could wrap Lightweight Charts into a component having sub components, please consult this [example](./react-complex-example).
```

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react.mdx
> +### Setup your React project - using Parcel
is there a reason why it starts from 3rd level of heading instead of 1st (or 2nd at least)?

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react.mdx
> +	"@babel/preset-react": "^7.10.1",
```suggestion
    "@babel/core": "^7.10.2",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
```

tabs vs spaces

2022-02-03 15:46 UTC, timocov commented on website/docs/tutorials/react.mdx
> +The example _React component_ on this page may not fit your requirements completely. Creating a general purpose declarative wrapper for Lightweight Chart's imperative API is a challenge, but hopefull
```suggestion
The example _React component_ on this page may not fit your requirements completely. Creating a general purpose declarative wrapper for Lightweight Charts' imperative API is a challenge, but hopefully you can adapt this example to your use case.
```

2022-02-03 15:46 UTC, timocov commented on website/src/pages/_react/chart-component.jsx
> +		chart.current.resize(400, 300);
hm, should we handle it at all if we use static size all the time? 🤔

2022-02-03 15:46 UTC, timocov commented on website/src/pages/_react/chart-component.jsx
> +	const chart = useRef();
do we need to use a ref for this simple case? or it is not react-way to create local variables?

2022-02-03 15:46 UTC, timocov commented on website/src/pages/_react/complex-example.jsx
> +				// eslint-disable-next-line no-unused-vars
will this line be displayed on the page as well?

2022-02-03 15:46 UTC, timocov commented on website/src/pages/_react/complex-example.jsx
> +				this._api.timeScale().fitContent();
probably we could omit this here just to make it simpler?

2022-02-03 15:46 UTC, timocov commented on website/src/pages/_react/complex-example.jsx
> +ChartContainer.displayName = 'ChartContainer';
is this react thing?

2022-02-03 18:18 UTC, tv-aponomarev commented on website/src/pages/_react/chart-component.jsx
> +		<ChartComponent data={data}></ChartComponent>
The data is passed to the component, but it is not used in the component:
```
export const ChartComponent = () => {
```
Maybe `ChartComponent` could be declared like this:
```
export function ChartComponent({ data }) {

}
```

2022-02-03 18:24 UTC, tv-aponomarev commented on website/src/pages/_react/chart-component.jsx
> +			window.addEventListener('resize', handleResize);
`handleResize` can be declared inside the effect as it is not used outside. It's better to leave as much as possible inside the effect to make it easier to find dependencies to re-run the effect.

2022-02-03 18:35 UTC, tv-aponomarev commented on website/src/pages/_react/chart-component.jsx
> +			setSeries(newSeries);
I think there is no need to keep the series in state. The data will be set at initialization and there is no need to keep track of the series as an effect dependency. Only the data can be tracked as a dependency to react to data changes and update the series. Therefore, the series can be stored in ref and not trigger a re-render.

2022-02-03 18:39 UTC, tv-aponomarev commented on website/src/pages/_react/complex-example.jsx
> +	}, [props]);
I think there is no need to use props as a dependency. This is close to "updating on every render" and the dependency array can be omitted entirely anywhere where properties are used as a dependency.

2022-02-03 18:41 UTC, tv-aponomarev commented on website/src/pages/_react/complex-example.jsx
> +	const series1 = useRef(null);
Maybe we can add code to demonstrate how this ref can be used.

2022-02-04 11:25 UTC, romfrancois commented on website/docs/tutorials/react-complex-example.mdx
> +Each _Series_ has its own options (for instance [AreaStyleOptions](/api/interfaces/AreaStyleOptions.md), [LineStyleOptions](/api/interfaces/LineStyleOptions.md), etc) in addition to [Price](../price-
I wanted to highlight that you could specify options when creating your serie but that you could also interact/change some options for both the price & time scale.

2022-02-04 11:33 UTC, romfrancois commented on website/docs/tutorials/react-complex-example.mdx
> +ChartContainer will be responsible for creating a **ref**[erence] that will hold functions to handle the lifecycle of the chart.
No I just tried to mix both the React wording "ref" by making it sound like a "reference" to something.
Just specifying "ref" sounded maybe too technical.

2022-02-04 11:35 UTC, romfrancois commented on website/docs/tutorials/react-complex-example.mdx
> +import Code from '!!raw-loader!./../../src/pages/_react/complex-example.jsx';
Good catch will remove.

2022-02-04 11:41 UTC, romfrancois commented on website/docs/tutorials/react.mdx
> +### Setup your React project - using Parcel
I didn't use 1 level because it didn't build the TOC on the right hand side of the page.
Will at least change it from level 3 to 2.

<img width="389" alt="Screenshot 2022-02-04 at 11 40 44" src="https://user-images.githubusercontent.com/3977635/152523114-da84eed3-ca04-42a2-8f57-eafdd8c1142c.png">

2022-02-04 11:42 UTC, romfrancois commented on website/docs/tutorials/react.mdx
> +// The following will create a web page accessible by default on http://localhost:1234/
Looks better indeed.

2022-02-04 11:47 UTC, romfrancois commented on website/src/pages/_react/complex-example.jsx
> +				// eslint-disable-next-line no-unused-vars
It will yes.

2022-02-04 11:48 UTC, romfrancois commented on website/src/pages/_react/complex-example.jsx
> +				this._api.timeScale().fitContent();
I'll remove it; I added it to make it more realistic but will remove it.

2022-02-04 11:50 UTC, romfrancois commented on website/src/pages/_react/complex-example.jsx
> +ChartContainer.displayName = 'ChartContainer';
I didn't know this one either but linter was complaining about it
```
Component definition is missing display nameeslint[react/display-name](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/display-name.md)
```

2022-02-04 11:54 UTC, romfrancois commented on website/src/pages/_react/chart-component.jsx
> +			setSeries(newSeries);
Good catch!

2022-02-07 15:53 UTC, romfrancois commented on website/src/pages/_react/chart-component.jsx
> +	const chart = useRef();
Removed as unnecessary.

2022-02-08 10:25 UTC, tv-aponomarev commented on website/src/pages/_react/advanced-react-example.jsx
> +	}, []);
An empty array means this will only be called on mount. The array needs to be completely excluded to update the parameters on every render as we don't want to detect real changes in the properties.

2022-02-09 17:17 UTC, timocov commented
Things to fix:

- scrollbars of the chart on windows
- borders inside the table on the chart
- add handling resize in advanced example
- (probably) fill the tutorials index page with some content
- Not for this PR but to fix later #1001

2022-02-14 09:52 UTC, romfrancois commented
@timocov would you mind checking both
> scrollbars of the chart on windows
> borders inside the table on the chart

2022-02-14 10:59 UTC, timocov requested changes

2022-02-14 10:59 UTC, timocov commented on website/src/pages/_react/simple-react-example.jsx
> +			newSeries.setData(data);
it seems that `data` here is a global object rather than what you're getting in `props`.

2022-02-14 10:59 UTC, timocov commented on website/src/pages/_react/simple-react-example.jsx
> +import styles from '../chart.module.css';
Is this related to the example? Couldn't we set it from the outside of this example code? Otherwise for consumers it will make no sense what is that

2022-02-14 10:59 UTC, timocov commented on website/src/pages/_react/advanced-react-example.jsx
> +import styles from '../chart.module.css';
the same for styles

2022-02-14 10:59 UTC, timocov commented on website/src/pages/chart.module.css
> +.ChartContainer * {
do we re-use these styles on the landing page?

2022-02-14 17:07 UTC, timocov commented on website/docs/tutorials/react/02-advanced.mdx
> +import { App } from "@site/src/pages/_react/advanced-react-example"
```suggestion
import { App } from '@site/src/pages/_react/advanced-react-example';
```

2022-02-16 17:10 UTC, timocov commented on website/docs/tutorials/react/01-simple.mdx
> +import styles from '../../../src/pages/chart.module.css';
```suggestion
import styles from '@site/src/pages/chart.module.css';
```

2022-02-16 17:10 UTC, timocov commented on website/docs/tutorials/react/01-simple.mdx
> +import { App } from '@site/src/pages/_react/simple-react-example'
```suggestion
import { App } from '@site/src/pages/_react/simple-react-example';
```

2022-02-16 17:10 UTC, timocov commented on website/docs/tutorials/react/02-advanced.mdx
> +The code above will produce a Series of type `line` Chart.
```suggestion
The code above will produce a line series.
```

2022-02-16 17:10 UTC, timocov commented on website/docs/tutorials/react/02-advanced.mdx
> +import styles from '../../../src/pages/chart.module.css';
```suggestion
import { App } from '@site/src/pages/_react/advanced-react-example';
import styles from '@site/src/pages/chart.module.css';
```

2022-02-16 17:28 UTC, timocov commented on website/src/pages/index.tsx
> +	const [chartContainerClassName, setChartContainerClassName] = React.useState<string>(`${styles.HeroChartContainer}`);
```suggestion
	const [chartContainerClassName, setChartContainerClassName] = React.useState<string>(styles.HeroChartContainer);
```

2022-02-16 17:36 UTC, timocov approved these changes

2022-02-16 17:41 UTC, merged