feat: add option to activate scroll on touch end event
tradingview/lightweight-charts pull request #972
Opened 2022-01-12 10:03 UTC by Ffloriel

**Type of PR:** enhancement

**PR checklist:**

- [x] Addresses an existing issue: fixes #106 #830
- [ ] Includes tests
- [x] Documentation update // in type

**Overview of change:**

- Update MouseEventHandler, separating the mouse and touch events (related to #106)
- Add _quick tracking option_, to activate scroll on touch end event instead of having to click after to reactivate the scroll.

2022-01-12 10:32 UTC, timocov requested changes

2022-01-12 10:32 UTC, timocov commented on src/gui/support-touch.ts
>  export const mobileTouch = getMobileTouch();
it seems that the only place where we use this variable as-is is `PaneWidget.mouseEnterEvent` method, do we still need to have it there since we migrated to event-based detection rather than browser-feature detection. probably we could remove it from there and rename this variable and the value?

2022-01-12 10:32 UTC, timocov commented on tests/e2e/coverage/coverage-config.ts
> -export const expectedCoverage = 89.5;
that's sad but understandable 🙂

2022-01-12 10:32 UTC, timocov commented on src/typings/_global-types/index.d.ts
> +}
I'd suggest to extract these types to a different folder like `src/types/dom-not-standarted/index.d.ts` since this file is more about global helpers but not related to the existent API so I'd prefer to extract this DOM extensions from it.

2022-01-12 10:32 UTC, timocov commented on src/gui/support-touch.ts
>  export const mobileTouch = getMobileTouch();
another please where this variable is still using is `src/gui/last-touch-or-mouse-event.ts`, but it seems that we shouldn't rely on a mobile touch there. it should be more whether a touch is supported or not

2022-01-12 10:32 UTC, timocov commented on src/gui/last-touch-or-mouse-event.ts
> +	return lastEventIsTouchValue;
shouldn't it be `!lastEventIsTouchValue` instead? but it seems that this function is not used anywhere so we can remove it 😄

2022-01-12 10:32 UTC, timocov commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
@kirchet do you remember what is the reason why we need to ignore middle-mouse-button scroll on chrome only?

2022-01-12 10:32 UTC, timocov commented on src/model/chart-model.ts
> +	activateScrollOnTouchEnd: boolean;
Hmm, for me it looks a bit confusing. Whether every touch end should activate scroll? What does "activate scroll" mean? Probably it shouldn't be a part of scroll options but another option on the root layer describing the behaviour. Maybe we can add something like `touchTrackingMode` and there 2 options: Quick, Long (not sure about names though). There we can also describe what does "tracking mode" mean to users. @kirchet what do you think?

2022-01-12 10:32 UTC, timocov commented on src/gui/mouse-event-handler.ts
> +		*/
```suggestion
	/**
	 * In Firefox mouse events dont't fire if the mouse position is outside of the browser's border.
	 * To prevent the mouse from hanging while pressed we're subscribing on the mouseleave event of the document element.
	 * We're subscribing on mouseleave, but this event is actually fired on mouseup outside of the browser's border.
	 */
```

looks like tabs issues here?

2022-01-12 10:32 UTC, timocov commented on src/model/chart-model.ts
> +	activateScrollOnTouchEnd: boolean;
or probably it might be even inclusive like "allowQuickTrackingMode" so if you activate tracking mode but didn't move the finger then it shouldn't disabled after touchend event

2022-01-12 11:10 UTC, kirchet commented on src/gui/support-touch.ts
>  export const mobileTouch = getMobileTouch();
Hm, not sure that it can be removed. Maybe in some cases it's needed to have "correct" initial `lastEventIsTouch()` value

2022-01-12 12:04 UTC, kirchet requested changes

2022-01-12 12:04 UTC, kirchet commented on src/model/chart-model.ts
> +	activateScrollOnTouchEnd: boolean;
I think we should add a new field like `trackingMode: TrackingModeOptions`. So we can extend it in the future without breaking changes

```
export const enum ExitTrackingModeBehaviour {
	OnTouchEnd,
	OnNextTap,
}

export interface TrackingModeOptions {
	exitMode: ExitTrackingModeBehaviour;
}
```

2022-01-12 12:18 UTC, kirchet commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
Because there was a bug in the Chrome only. After zooming a page and middle button clicking the cursor mode incorrectly changed to "native scroll by midde button mode"

2022-01-12 12:21 UTC, kirchet commented on src/model/chart-model.ts
> +	activateScrollOnTouchEnd: boolean;
I think we should add a new field like `trackingMode`. So we can extend in in the future.

```
export const enum TrackingExitMode {
    OnTouchEnd,
    OnNextTap,
}
export interface TrackingModeOptions {
    exitMode: TrackingExitMode;
}
```

2022-01-12 12:22 UTC, kirchet commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
Not sure if it's needed in lightweight-charts

2022-01-12 16:24 UTC, timocov commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
@Ffloriel could you check the case above please?

2022-01-12 19:57 UTC, kirchet commented on src/gui/support-touch.ts
>  export const mobileTouch = getMobileTouch();
Ah, yes, I agree

2022-01-12 20:10 UTC, kirchet commented on src/gui/support-touch.ts
>  export const mobileTouch = getMobileTouch();
Seems that it's not used now anywhere, so I'm resolving this thread

2022-01-12 20:11 UTC, kirchet commented on src/gui/last-touch-or-mouse-event.ts
> +	return lastEventIsTouchValue;
The wnole module is removed, so this thread is resolved

2022-01-13 13:42 UTC, Ffloriel commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
Behavior is the same on Chrome and Firefox. I don't see the issue with the middle button.

2022-01-13 14:02 UTC, Ffloriel commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
nevermind, I can see the issue on windows.

2022-01-13 14:29 UTC, kirchet commented on src/gui/pane-widget.ts
> +		this._startTrackPoint = null;
Or from all mouse handlers because its name is `_onMouseEvent` 🙂

2022-01-13 15:04 UTC, Ffloriel commented on src/gui/pane-widget.ts
> +		this._startTrackPoint = null;
:thinking_face: ok, I see what you mean. We only preventing the scroll for pressedMouseMoveEvent so that's why I originally only reset it here. Other events should not be affected but the logic makes sense to do it also for the other ones

2022-01-14 17:53 UTC, kirchet commented on src/helpers/events.ts
> +			// prevent incorrect scrolling event
I think it's not directly related to this PR, so if there is an issue we can fix it in another PR

2022-01-14 17:53 UTC, kirchet approved these changes

2022-01-17 16:28 UTC, timocov commented on src/model/chart-model.ts
> +    OnNextTap,
```suggestion
	OnTouchEnd,
	/**
	 * Tracking Mode will be deactivated on the next tap event.
	 */
	OnNextTap,
```

looks like tabs vs spaces issue

2022-01-17 16:28 UTC, timocov commented on src/model/chart-model.ts
> +	/** @inheritdoc TrackingExitMode
what does this thing for the docs? should we apply it for other options as well (in different PR of course)?

2022-01-17 16:28 UTC, timocov commented on src/model/chart-model.ts
> +	 * @defaultValue `TrackingExitMode.OnNextTap`
```suggestion
	 * @defaultValue {@link TrackingExitMode.OnNextTap}
```

shouldn't it be like that instead?

2022-01-17 16:28 UTC, timocov commented on src/model/chart-model.ts
> +export const enum TrackingExitMode {
shouldn't it be TrackingModeExitMode? 😂

2022-01-18 16:42 UTC, Ffloriel commented on src/model/chart-model.ts
> +	 * @defaultValue `TrackingExitMode.OnNextTap`
yes, it's better if it's a link

2022-01-18 16:44 UTC, Ffloriel commented on src/model/chart-model.ts
> +	/** @inheritdoc TrackingExitMode
it basically copies the description. Avoid having to duplicate it. There's an issue with the eslint plugin though (https://github.com/microsoft/tsdoc/issues/220), because typedoc and tsdoc have a different syntax for it.

2022-01-18 16:50 UTC, timocov commented on src/model/chart-model.ts
> +	/** @inheritdoc TrackingExitMode
Ah, I see, thanks! At least we can format it properly, or it is formatted so because we need to disable linter for this line? 😂

2022-01-18 17:08 UTC, Ffloriel commented on src/model/chart-model.ts
> +	/** @inheritdoc TrackingExitMode
ahah yep, unfortunately it's to disable the linter

2022-01-18 17:37 UTC, timocov approved these changes

2022-01-19 10:04 UTC, merged