Add documentation website landing page
tradingview/lightweight-charts pull request #983
Opened 2022-01-21 10:08 UTC by edew

**Type of PR:** enhancement

**PR checklist:**

- [ ] Addresses an existing issue: fixes #
- [ ] Includes tests
- [x] Documentation update

**Overview of change:**

This PR adds a fresh landing page for the documentation website.

**Is there anything you'd like reviewers to focus on?**

* I'm styling the svg icons in the page with CSS so they change correctly for light/dark mode, but the logo in the navbar can't be styled like this as Docusaurus loads it in an `img` tag so the navbar loads two different static svg files.
* The chart data doesn't match the design perfectly. Do we think that's OK?

2022-01-24 13:28 UTC, timocov requested changes

2022-01-24 13:28 UTC, timocov commented on package.json
> +    "eslint-plugin-react": "^7.28.0",
```suggestion
    "eslint-plugin-react": "~7.28.0",
```

2022-01-24 13:28 UTC, timocov commented on website/docusaurus.config.js
> -					src: 'img/lightweight-charts-logo.svg',
so we need to remove a code above which copies this file, see a statement after comment `copy logo file to static folder so we can refer to it in the config` above

2022-01-24 13:28 UTC, timocov commented on website/package.json
> +    "@docusaurus/module-type-aliases": "^2.0.0-beta.14",
```suggestion
    "@docusaurus/module-type-aliases": "2.0.0-beta.13",
```

2022-01-24 13:28 UTC, timocov commented on website/package.json
> +    "lightweight-charts": "^3.7.0",
```suggestion
    "lightweight-charts": "~3.7.0",
```

2022-01-24 13:28 UTC, timocov commented on website/docusaurus.config.js
> +					srcDark: 'img/logo-light.png',
maybe we can use svg icon instead? not too sure that use raster images as logos with predefined static (quite small) size is a good idea though

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.module.css
> +	stroke: var(--LargeIconSvgFillColor);
shouldn't it be defined in an svg file instead? 🤔

2022-01-24 13:28 UTC, timocov commented on website/static/img/logo.svg
> +<svg class="logo-svg" width="92" height="56" viewBox="0 0 92 56" fill="none" xmlns="http://www.w3.org/2000/svg">
please apply svgo for this file (or internal svg optimization tool - see `tools/svg-tools`)

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.module.css
> +		background: var(--HeroTextBackgroundColor);
is it expected that bg color is changed when a width is changed? I'm just curios, I'm not big expert in that 😄

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.module.css
> +.HeroContainer {
since we're going to add more css files to about pages, probably we need to add stylelint to the repo? what do you think?

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.tsx
> +const data = { orangeData: [{ value: 33, time: 1628005368 as UTCTimestamp }, { value: 33.49774076716826, time: 1628610168 as UTCTimestamp }, { value: 33.00544183567645, time: 1629214968 as UTCTimesta
would you mind to format it in several lines or/and even extract it to a separate file please?

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.tsx
> +				: { background: { color: 'rgba(248, 249, 253, 1)' }, textColor: '#000000' };
is seems that this is defined twice, maybe we can extract it to a function?

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.tsx
> +		<svg width="115" height="103" viewBox="0 0 115 104" fill="none" xmlns="http://www.w3.org/2000/svg">
is there a reason why we don't extract all these svgs to separate files instead?

2022-01-24 13:28 UTC, timocov commented on website/src/pages/index.tsx
> +// eslint-disable-next-line import/no-default-export
probably for jsx/tsx (btw we we don't use tsx for components?) we need to disable this rule in eslint? we can use either overrides or local eslint config files for that (to specify it only for pages for example)

2022-01-24 14:05 UTC, subzey commented on website/src/css/custom.css
> +.logo-svg path {
The inline SVGs can be recolored much easier! Just mark the necessary `fill`s and `stroke`s as `currentcolor` and now the entire svg color can be controlled using a single `color` property.

https://jsfiddle.net/subzey/mwj30uy9/

2022-01-24 14:12 UTC, subzey commented on website/src/pages/index.module.css
> +	.LargeCard:last-of-type {
Not really an issue, rather a reminder:

This selector may behave not as you'd expect. `.LargeCard:last-of-type` doesn't mean "The last child of those who have the class LargeCard". It's rather "The last child with the <unspecified> tagname if by chance is has the class LargeCard"

2022-01-24 14:36 UTC, subzey commented on website/src/pages/index.module.css
> +@media (min-width: 1280px) {
@timocov Could this page be shown inside an `iframe`?

Firefox is known to have fractional viewport sizes on non-integer DPRs. See as a demo: https://bl.ocks.org/subzey/ffa9cfda0efc8e09bb3c19a155d610ca

The workaround is really simple:

```css
@media (min-width: 1279.5px) {
```

(also it helps those poor souls who cannot remember is `min-width` a `<` or `<=`)

2022-01-24 14:47 UTC, timocov commented on website/src/pages/index.module.css
> +@media (min-width: 1280px) {
> Could this page be shown inside an iframe?

No, I don't think so. I mean, maybe someone could put it into an iframe, but we aren't going to do this.

2022-01-24 14:56 UTC, subzey commented on website/src/pages/index.module.css
> +	.SmallCard:nth-of-type(4) {
The stylization based on the element order may be really painful to maintain. If something is changed in the future the entire block of rules should be checked and fixed.

Also, there can be a stray `span` or `div` elements inserted by libraries and browser extensions.

> Here's an example of such behavior: https://bl.ocks.org/subzey/752f24df13784e4f3517e7237aad33a1. Open it up in Google Chrome and the translate the page into English. The bang sign is red after the translation instead of the username.

2022-01-24 15:55 UTC, edew commented on website/src/pages/index.module.css
> +		background: var(--HeroTextBackgroundColor);
Good point - this can be moved to the definition outside the media query I think.

2022-01-24 15:56 UTC, edew commented on website/src/pages/index.tsx
> +		<svg width="115" height="103" viewBox="0 0 115 104" fill="none" xmlns="http://www.w3.org/2000/svg">
No I think they can be extracted. I will do that.

2022-01-24 18:10 UTC, edew commented on website/src/pages/index.module.css
> +.HeroContainer {
Yes that's a good idea. Shall we do it in this PR or in another one?

2022-01-25 15:44 UTC, edew commented on website/src/pages/index.module.css
> +	.SmallCard:nth-of-type(4) {
Good point. I will replace these selectors with specific classes. I think that will be easier to maintain/harder to break accidentally.

2022-01-25 15:44 UTC, timocov commented on website/src/css/custom.css
> +	--PrimaryButtonColor: rgba(41, 98, 255, 1);
looks like spaces/tabs issue

2022-01-25 15:44 UTC, timocov commented on website/src/css/custom.css
> +.logo-svg path {
it looks like this is still valid?

2022-01-25 15:44 UTC, timocov commented on website/src/pages/index.module.css
> +.HeroContainer {
we can do it as a separate PR

2022-01-25 15:44 UTC, timocov commented on website/src/pages/index.module.css
> +	background: rgba(30, 83, 229, 1);
shouldn't colors be a part of the theme? 🤔 I mean color values

2022-01-25 15:44 UTC, timocov commented on website/src/pages/index.module.css
> +@media (min-width: 768px) {
shouldn't this be the same as below with 0.5?

2022-01-25 15:44 UTC, timocov commented on .eslintrc.js
> +		'plugin:react/recommended',
will it work for tsx files as well right?

2022-01-25 15:44 UTC, timocov commented on website/docusaurus.config.js
> +					srcDark: 'img/logo-dark.svg',
do you know the difference between light and dark icons? is it the color only?

2022-01-25 15:44 UTC, timocov commented on website/docusaurus.config.js
> -					src: 'img/lightweight-charts-logo.svg',
looks like it is still valid

2022-01-25 15:44 UTC, timocov commented on website/src/pages/index.tsx
> +		<svg width="115" height="103" viewBox="0 0 115 104" fill="none" xmlns="http://www.w3.org/2000/svg">
Looks like we need to use https://www.npmjs.com/package/react-svg-loader for svg to make them inlined?

2022-01-25 16:15 UTC, timocov commented on website/src/pages/index.tsx
> +		<svg width="115" height="103" viewBox="0 0 115 104" fill="none" xmlns="http://www.w3.org/2000/svg">
Oh cool, looks like they have built-in webpack loader https://react-svgr.com/docs/webpack/

2022-01-25 16:53 UTC, edew commented on website/docusaurus.config.js
> +					srcDark: 'img/logo-dark.svg',
Yes, the colours are different.

2022-01-25 17:06 UTC, edew commented on .eslintrc.js
> +		'plugin:react/recommended',
Yep 👍

2022-01-25 17:08 UTC, edew commented on website/src/pages/index.module.css
> +	background: rgba(30, 83, 229, 1);
I only extracted vars for colors that are used in multiple rules for now

2022-01-27 14:32 UTC, edew commented on website/docusaurus.config.js
> +					srcDark: 'img/logo-dark.svg',
Docusaurus handles the loading of the logo image in the navbar. Because it loads it into a `<img>` we can't style the svg color with css.

2022-01-27 14:45 UTC, timocov commented on website/src/pages/index.tsx
> +				c.timeScale().setVisibleLogicalRange({ from: 1, to: data.orangeData.length - 2 });
See https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#lockvisibletimerangeonresize, it seems that this is what you need instead 🙂

2022-01-27 17:02 UTC, timocov approved these changes

2022-01-27 17:12 UTC, merged